run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/TRC-Loop/cairn

issues:
  exclude-dirs:
    - internal/store # sqlc-generated code
