// SPDX-License-Identifier: AGPL-3.0-or-later
package api

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"strconv"
	"time"

	"github.com/TRC-Loop/cairn/internal/auth"
	"github.com/TRC-Loop/cairn/internal/incident"
	"github.com/TRC-Loop/cairn/internal/store"
	"github.com/go-chi/chi/v5"
)

type IncidentsHandler struct {
	q      *store.Queries
	svc    *incident.Service
	logger *slog.Logger
}

func NewIncidentsHandler(q *store.Queries, svc *incident.Service, logger *slog.Logger) *IncidentsHandler {
	return &IncidentsHandler{q: q, svc: svc, logger: logger}
}

type incidentResponse struct {
	ID                  int64          `json:"id"`
	DisplayID           string         `json:"display_id"`
	Title               string         `json:"title"`
	Status              string         `json:"status"`
	Severity            string         `json:"severity"`
	StartedAt           time.Time      `json:"started_at"`
	ResolvedAt          *time.Time     `json:"resolved_at"`
	AutoCreated         bool           `json:"auto_created"`
	TriggeringCheckID   *int64         `json:"triggering_check_id"`
	TriggeringCheck     *checkSummary  `json:"triggering_check"`
	CreatedByUserID     *int64         `json:"created_by_user_id"`
	AffectedCheckCount  int            `json:"affected_check_count"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
}

type checkSummary struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	LastStatus string `json:"last_status"`
}

type incidentUpdateResponse struct {
	ID             int64     `json:"id"`
	IncidentID     int64     `json:"incident_id"`
	Status         string    `json:"status"`
	Message        string    `json:"message"`
	MessageHTML    string    `json:"message_html"`
	PostedByUserID *int64    `json:"posted_by_user_id"`
	AutoGenerated  bool      `json:"auto_generated"`
	CreatedAt      time.Time `json:"created_at"`
}

func toIncidentResponse(in store.Incident, affectedCount int, trig *checkSummary, idFormat string) incidentResponse {
	out := incidentResponse{
		ID:                 in.ID,
		DisplayID:          incident.FormatID(idFormat, in.ID, in.StartedAt),
		Title:              in.Title,
		Status:             in.Status,
		Severity:           in.Severity,
		StartedAt:          in.StartedAt,
		AutoCreated:        in.AutoCreated,
		AffectedCheckCount: affectedCount,
		TriggeringCheck:    trig,
		CreatedAt:          in.CreatedAt,
		UpdatedAt:          in.UpdatedAt,
	}
	if in.ResolvedAt.Valid {
		t := in.ResolvedAt.Time
		out.ResolvedAt = &t
	}
	if in.TriggeringCheckID.Valid {
		v := in.TriggeringCheckID.Int64
		out.TriggeringCheckID = &v
	}
	if in.CreatedByUserID.Valid {
		v := in.CreatedByUserID.Int64
		out.CreatedByUserID = &v
	}
	return out
}

func toUpdateResponse(u store.IncidentUpdate) incidentUpdateResponse {
	out := incidentUpdateResponse{
		ID:            u.ID,
		IncidentID:    u.IncidentID,
		Status:        u.Status,
		Message:       u.Message,
		MessageHTML:   string(incident.RenderMarkdown(u.Message)),
		AutoGenerated: u.AutoGenerated,
		CreatedAt:     u.CreatedAt,
	}
	if u.PostedByUserID.Valid {
		v := u.PostedByUserID.Int64
		out.PostedByUserID = &v
	}
	return out
}

func (h *IncidentsHandler) idFormat(ctx context.Context) string {
	s, err := h.q.GetSystemSettings(ctx)
	if err != nil || s.IncidentIDFormat == "" {
		return incident.DefaultIDFormat
	}
	return s.IncidentIDFormat
}

func (h *IncidentsHandler) loadTriggeringCheck(ctx context.Context, in store.Incident) *checkSummary {
	if !in.TriggeringCheckID.Valid {
		return nil
	}
	c, err := h.q.GetCheck(ctx, in.TriggeringCheckID.Int64)
	if err != nil {
		return nil
	}
	return &checkSummary{ID: c.ID, Name: c.Name, Type: c.Type, LastStatus: c.LastStatus}
}

func (h *IncidentsHandler) List(w http.ResponseWriter, r *http.Request) {
	status := r.URL.Query().Get("status")
	if status == "" {
		status = "all"
	}
	limit := int64(50)
	if v := r.URL.Query().Get("limit"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil && n > 0 && n <= 200 {
			limit = n
		}
	}
	offset := int64(0)
	if v := r.URL.Query().Get("offset"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil && n >= 0 {
			offset = n
		}
	}

	var rows []store.Incident
	var err error
	switch status {
	case "active":
		rows, err = h.q.ListActiveIncidents(r.Context())
	case "resolved":
		rows, err = h.q.ListRecentResolvedIncidents(r.Context(), limit)
	case "all":
		rows, err = h.q.ListIncidents(r.Context(), store.ListIncidentsParams{Limit: limit, Offset: offset})
	default:
		writeError(w, http.StatusBadRequest, CodeBadRequest, "invalid status", nil)
		return
	}
	if err != nil {
		h.logger.Error("list incidents failed", "status", status, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}

	idFormat := h.idFormat(r.Context())
	out := make([]incidentResponse, 0, len(rows))
	for _, in := range rows {
		ids, _ := h.q.ListAffectedCheckIDsForIncident(r.Context(), in.ID)
		out = append(out, toIncidentResponse(in, len(ids), h.loadTriggeringCheck(r.Context(), in), idFormat))
	}
	writeJSON(w, http.StatusOK, map[string]any{"incidents": out, "total": len(out)})
}

func (h *IncidentsHandler) Get(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	in, err := h.q.GetIncident(r.Context(), id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			writeError(w, http.StatusNotFound, CodeNotFound, "not found", nil)
			return
		}
		h.logger.Error("get incident failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	updates, err := h.q.ListUpdatesForIncident(r.Context(), id)
	if err != nil {
		h.logger.Error("list incident updates failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	checks, err := h.q.ListChecksForIncident(r.Context(), id)
	if err != nil {
		h.logger.Error("list incident checks failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	checksOut := make([]checkResponse, 0, len(checks))
	for _, c := range checks {
		checksOut = append(checksOut, toCheckResponse(c, false))
	}
	updatesOut := make([]incidentUpdateResponse, 0, len(updates))
	for _, u := range updates {
		updatesOut = append(updatesOut, toUpdateResponse(u))
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"incident":         toIncidentResponse(in, len(checks), h.loadTriggeringCheck(r.Context(), in), h.idFormat(r.Context())),
		"updates":          updatesOut,
		"affected_checks":  checksOut,
	})
}

type incidentCreateRequest struct {
	Title            string  `json:"title"`
	Severity         string  `json:"severity"`
	InitialMessage   string  `json:"initial_message"`
	AffectedCheckIDs []int64 `json:"affected_check_ids"`
}

func (h *IncidentsHandler) Create(w http.ResponseWriter, r *http.Request) {
	var req incidentCreateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, CodeInvalidJSON, "invalid json", nil)
		return
	}
	fields := map[string]string{}
	if l := len(req.Title); l < 1 {
		fields["title"] = FieldRequired
	} else if l > 200 {
		fields["title"] = FieldTooLong
	}
	if !incident.Severity(req.Severity).Valid() {
		fields["severity"] = FieldInvalidValue
	}
	if l := len(req.InitialMessage); l < 1 {
		fields["initial_message"] = FieldRequired
	} else if l > 2000 {
		fields["initial_message"] = FieldTooLong
	}
	if len(req.AffectedCheckIDs) < 1 {
		fields["affected_check_ids"] = FieldRequired
	} else {
		for _, id := range req.AffectedCheckIDs {
			if _, err := h.q.GetCheck(r.Context(), id); err != nil {
				fields["affected_check_ids"] = FieldInvalidValue
				break
			}
		}
	}
	if len(fields) > 0 {
		writeError(w, http.StatusBadRequest, CodeValidationFailed, "validation failed", fields)
		return
	}

	user, _ := auth.UserFromContext(r.Context())
	in, err := h.svc.CreateManual(r.Context(), incident.CreateIncidentInput{
		Title:            req.Title,
		Severity:         incident.Severity(req.Severity),
		InitialMessage:   req.InitialMessage,
		AffectedCheckIDs: req.AffectedCheckIDs,
		CreatedByUserID:  user.ID,
	})
	if err != nil {
		h.logger.Error("create incident failed", "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	updates, _ := h.q.ListUpdatesForIncident(r.Context(), in.ID)
	updatesOut := make([]incidentUpdateResponse, 0, len(updates))
	for _, u := range updates {
		updatesOut = append(updatesOut, toUpdateResponse(u))
	}
	h.logger.Info("incident created", "id", in.ID, "user_id", user.ID, "affected_count", len(req.AffectedCheckIDs))
	writeJSON(w, http.StatusCreated, map[string]any{
		"incident": toIncidentResponse(in, len(req.AffectedCheckIDs), nil, h.idFormat(r.Context())),
		"updates":  updatesOut,
	})
}

type incidentPatchRequest struct {
	Title    *string `json:"title"`
	Severity *string `json:"severity"`
}

func (h *IncidentsHandler) Update(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	in, err := h.q.GetIncident(r.Context(), id)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			writeError(w, http.StatusNotFound, CodeNotFound, "not found", nil)
			return
		}
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	var req incidentPatchRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, CodeInvalidJSON, "invalid json", nil)
		return
	}
	title := in.Title
	severity := in.Severity
	if req.Title != nil {
		title = *req.Title
	}
	if req.Severity != nil {
		severity = *req.Severity
	}
	fields := map[string]string{}
	if l := len(title); l < 1 {
		fields["title"] = FieldRequired
	} else if l > 200 {
		fields["title"] = FieldTooLong
	}
	if !incident.Severity(severity).Valid() {
		fields["severity"] = FieldInvalidValue
	}
	if len(fields) > 0 {
		writeError(w, http.StatusBadRequest, CodeValidationFailed, "validation failed", fields)
		return
	}
	if err := h.q.UpdateIncidentMetadata(r.Context(), store.UpdateIncidentMetadataParams{
		Title: title, Severity: severity, ID: id,
	}); err != nil {
		h.logger.Error("update incident failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	updated, _ := h.q.GetIncident(r.Context(), id)
	ids, _ := h.q.ListAffectedCheckIDsForIncident(r.Context(), id)
	h.logger.Info("incident updated", "id", id)
	writeJSON(w, http.StatusOK, map[string]any{
		"incident": toIncidentResponse(updated, len(ids), h.loadTriggeringCheck(r.Context(), updated), h.idFormat(r.Context())),
	})
}

type incidentAddUpdateRequest struct {
	Message   string  `json:"message"`
	NewStatus *string `json:"new_status"`
}

func (h *IncidentsHandler) AddUpdate(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	var req incidentAddUpdateRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, CodeInvalidJSON, "invalid json", nil)
		return
	}
	fields := map[string]string{}
	if l := len(req.Message); l < 1 {
		fields["message"] = FieldRequired
	} else if l > 2000 {
		fields["message"] = FieldTooLong
	}
	var ns *incident.Status
	if req.NewStatus != nil && *req.NewStatus != "" {
		s := incident.Status(*req.NewStatus)
		if !s.Valid() {
			fields["new_status"] = FieldInvalidValue
		} else {
			ns = &s
		}
	}
	if len(fields) > 0 {
		writeError(w, http.StatusBadRequest, CodeValidationFailed, "validation failed", fields)
		return
	}
	user, _ := auth.UserFromContext(r.Context())
	upd, err := h.svc.PostUpdate(r.Context(), incident.PostUpdateInput{
		IncidentID:   id,
		Message:      req.Message,
		NewStatus:    ns,
		PostedByUser: user.ID,
	})
	if err != nil {
		if errors.Is(err, incident.ErrInvalidTransition) {
			writeError(w, http.StatusBadRequest, CodeInvalidStatusTransition, "invalid status transition", nil)
			return
		}
		if errors.Is(err, sql.ErrNoRows) {
			writeError(w, http.StatusNotFound, CodeNotFound, "not found", nil)
			return
		}
		h.logger.Error("post incident update failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	in, _ := h.q.GetIncident(r.Context(), id)
	ids, _ := h.q.ListAffectedCheckIDsForIncident(r.Context(), id)
	h.logger.Info("incident update posted", "id", id, "user_id", user.ID, "transitioned", ns != nil)
	writeJSON(w, http.StatusCreated, map[string]any{
		"update":   toUpdateResponse(upd),
		"incident": toIncidentResponse(in, len(ids), h.loadTriggeringCheck(r.Context(), in), h.idFormat(r.Context())),
	})
}

type incidentAddAffectedRequest struct {
	CheckID int64 `json:"check_id"`
}

func (h *IncidentsHandler) AddAffected(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	var req incidentAddAffectedRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.CheckID <= 0 {
		writeError(w, http.StatusBadRequest, CodeInvalidJSON, "invalid json", nil)
		return
	}
	if _, err := h.q.GetIncident(r.Context(), id); err != nil {
		writeError(w, http.StatusNotFound, CodeNotFound, "not found", nil)
		return
	}
	if _, err := h.q.GetCheck(r.Context(), req.CheckID); err != nil {
		writeError(w, http.StatusBadRequest, CodeValidationFailed, "check not found", map[string]string{"check_id": FieldNotFound})
		return
	}
	if err := h.q.LinkCheckToIncident(r.Context(), store.LinkCheckToIncidentParams{
		IncidentID: id, CheckID: req.CheckID,
	}); err != nil {
		h.logger.Error("link check to incident failed", "incident_id", id, "check_id", req.CheckID, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *IncidentsHandler) RemoveAffected(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	raw := chi.URLParam(r, "check_id")
	checkID, err := strconv.ParseInt(raw, 10, 64)
	if err != nil || checkID <= 0 {
		writeError(w, http.StatusBadRequest, CodeBadRequest, "invalid check_id", nil)
		return
	}
	if err := h.q.UnlinkCheckFromIncident(r.Context(), store.UnlinkCheckFromIncidentParams{
		IncidentID: id, CheckID: checkID,
	}); err != nil {
		h.logger.Error("unlink check from incident failed", "incident_id", id, "check_id", checkID, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

func (h *IncidentsHandler) Delete(w http.ResponseWriter, r *http.Request) {
	id, ok := parseIDParam(w, r)
	if !ok {
		return
	}
	if err := h.q.DeleteIncident(r.Context(), id); err != nil {
		h.logger.Error("delete incident failed", "id", id, "err", err)
		writeError(w, http.StatusInternalServerError, CodeInternalError, "internal error", nil)
		return
	}
	h.logger.Info("incident deleted", "id", id)
	w.WriteHeader(http.StatusNoContent)
}
