// SPDX-License-Identifier: AGPL-3.0-or-later
package incident

import (
	"context"
	"database/sql"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"time"

	"github.com/TRC-Loop/cairn/internal/store"
	_ "modernc.org/sqlite"
)

var gooseDirective = regexp.MustCompile(`(?m)^\s*--\s*\+goose.*$`)

func openTestDB(t *testing.T) (*sql.DB, *store.Queries) {
	t.Helper()
	dir := t.TempDir()
	path := filepath.Join(dir, "test.db")
	db, err := sql.Open("sqlite", "file:"+path+"?_pragma=foreign_keys(1)")
	if err != nil {
		t.Fatalf("open: %v", err)
	}
	t.Cleanup(func() { db.Close() })
	applyMigrations(t, db)
	return db, store.New(db)
}

func applyMigrations(t *testing.T, db *sql.DB) {
	t.Helper()
	root := findRepoRoot(t)
	files, err := filepath.Glob(filepath.Join(root, "migrations", "*.sql"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	for _, f := range files {
		raw, err := os.ReadFile(f)
		if err != nil {
			t.Fatalf("read %s: %v", f, err)
		}
		up := extractUp(string(raw))
		if _, err := db.Exec(up); err != nil {
			t.Fatalf("apply %s: %v", f, err)
		}
	}
}

func extractUp(content string) string {
	idx := strings.Index(content, "-- +goose Down")
	if idx == -1 {
		idx = len(content)
	}
	return gooseDirective.ReplaceAllString(content[:idx], "")
}

func findRepoRoot(t *testing.T) string {
	t.Helper()
	dir, _ := os.Getwd()
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		p := filepath.Dir(dir)
		if p == dir {
			t.Fatalf("go.mod not found")
		}
		dir = p
	}
}

func newTestService(t *testing.T) (*Service, *store.Queries, *sql.DB) {
	t.Helper()
	db, q := openTestDB(t)
	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	return NewService(db, q, logger, nil), q, db
}

func createCheck(t *testing.T, q *store.Queries, name string) store.Check {
	t.Helper()
	c, err := q.CreateCheck(context.Background(), store.CreateCheckParams{
		Name:              name,
		Type:              "http",
		Enabled:           true,
		IntervalSeconds:   60,
		TimeoutSeconds:    10,
		FailureThreshold:  3,
		RecoveryThreshold: 1,
		ConfigJson:        `{}`,
	})
	if err != nil {
		t.Fatalf("create check: %v", err)
	}
	return c
}

func TestCreateManualHappyPath(t *testing.T) {
	svc, q, _ := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")

	inc, err := svc.CreateManual(ctx, CreateIncidentInput{
		Title:            "Manual problem",
		Severity:         SeverityMinor,
		InitialMessage:   "Kicking off investigation",
		AffectedCheckIDs: []int64{c.ID},
	})
	if err != nil {
		t.Fatalf("create manual: %v", err)
	}
	if inc.ID == 0 {
		t.Fatal("incident not assigned an ID")
	}
	if inc.Status != string(StatusInvestigating) {
		t.Fatalf("expected investigating, got %s", inc.Status)
	}
	if inc.AutoCreated {
		t.Fatal("manual incident should not be auto_created")
	}

	updates, err := q.ListUpdatesForIncident(ctx, inc.ID)
	if err != nil {
		t.Fatalf("list updates: %v", err)
	}
	if len(updates) != 1 {
		t.Fatalf("expected 1 update, got %d", len(updates))
	}
	if updates[0].AutoGenerated {
		t.Fatal("initial manual update should not be auto_generated")
	}

	ids, err := q.ListAffectedCheckIDsForIncident(ctx, inc.ID)
	if err != nil {
		t.Fatalf("list affected: %v", err)
	}
	if len(ids) != 1 || ids[0] != c.ID {
		t.Fatalf("expected [%d], got %v", c.ID, ids)
	}
}

func TestCreateAutoIsIdempotent(t *testing.T) {
	svc, q, _ := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")

	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto 1: %v", err)
	}
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto 2: %v", err)
	}
	if id1 != id2 {
		t.Fatalf("expected same incident, got %d != %d", id1, id2)
	}

	incs, err := q.ListActiveIncidents(ctx)
	if err != nil {
		t.Fatalf("list active: %v", err)
	}
	if len(incs) != 1 {
		t.Fatalf("expected 1 active incident, got %d", len(incs))
	}
	if !incs[0].AutoCreated {
		t.Fatal("expected auto_created=true")
	}
	if !incs[0].TriggeringCheckID.Valid || incs[0].TriggeringCheckID.Int64 != c.ID {
		t.Fatalf("expected triggering_check_id %d, got %v", c.ID, incs[0].TriggeringCheckID)
	}
}

func TestTransitionResolvedSetsResolvedAt(t *testing.T) {
	svc, q, _ := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")

	id, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}

	if err := svc.Transition(ctx, id, StatusResolved, nil, "recovered"); err != nil {
		t.Fatalf("transition: %v", err)
	}

	inc, err := q.GetIncident(ctx, id)
	if err != nil {
		t.Fatalf("get: %v", err)
	}
	if inc.Status != string(StatusResolved) {
		t.Fatalf("expected resolved, got %s", inc.Status)
	}
	if !inc.ResolvedAt.Valid {
		t.Fatal("expected resolved_at to be set")
	}
}

func TestPostUpdateSameStatusKeepsStatus(t *testing.T) {
	svc, q, _ := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	id, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	investigating := StatusInvestigating
	upd, err := svc.PostUpdate(ctx, PostUpdateInput{
		IncidentID: id,
		Message:    "still investigating",
		NewStatus:  &investigating,
	})
	if err != nil {
		t.Fatalf("post update: %v", err)
	}
	if upd.Status != string(StatusInvestigating) {
		t.Fatalf("update status = %s", upd.Status)
	}
	inc, _ := q.GetIncident(ctx, id)
	if inc.Status != string(StatusInvestigating) {
		t.Fatalf("incident status = %s", inc.Status)
	}
	if inc.ResolvedAt.Valid {
		t.Fatal("resolved_at should remain unset")
	}
	updates, _ := q.ListUpdatesForIncident(ctx, id)
	if len(updates) != 2 {
		t.Fatalf("expected 2 updates (auto + same-state), got %d", len(updates))
	}
}

func resolveAndBackdate(t *testing.T, svc *Service, db *sql.DB, ctx context.Context, id int64, ago time.Duration) {
	t.Helper()
	if err := svc.Transition(ctx, id, StatusResolved, nil, "fixed"); err != nil {
		t.Fatalf("resolve: %v", err)
	}
	at := time.Now().UTC().Add(-ago)
	if _, err := db.ExecContext(ctx, "UPDATE incidents SET resolved_at = ? WHERE id = ?", at, id); err != nil {
		t.Fatalf("backdate: %v", err)
	}
}

func setReopenMode(t *testing.T, db *sql.DB, mode string, windowSec int64) {
	t.Helper()
	if _, err := db.Exec("UPDATE system_settings SET incident_reopen_mode = ?, incident_reopen_window_seconds = ? WHERE id = 1", mode, windowSec); err != nil {
		t.Fatalf("set reopen mode: %v", err)
	}
}

func TestReopenAlwaysWithinWindow(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 5*time.Minute)
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 != id2 {
		t.Fatalf("expected reopen of %d, got new %d", id1, id2)
	}
	inc, _ := q.GetIncident(ctx, id1)
	if inc.Status != string(StatusInvestigating) {
		t.Fatalf("status = %s", inc.Status)
	}
	if inc.ResolvedAt.Valid {
		t.Fatal("resolved_at should be cleared")
	}
}

func TestReopenNeverAlwaysCreatesNew(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	setReopenMode(t, db, "never", 3600)
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 5*time.Minute)
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 == id2 {
		t.Fatal("expected new incident, got reopen")
	}
	_ = q
}

func TestReopenOutsideWindowCreatesNew(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 2*time.Hour)
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 == id2 {
		t.Fatal("expected new incident outside window")
	}
}

func TestReopenFlappingHighDownReopens(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	setReopenMode(t, db, "flapping_only", 3600)
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 5*time.Minute)
	now := time.Now().UTC()
	for i := 0; i < 6; i++ {
		_ = q.InsertCheckResult(ctx, store.InsertCheckResultParams{CheckID: c.ID, CheckedAt: now.Add(-time.Duration(i) * time.Minute), Status: "down"})
	}
	for i := 0; i < 2; i++ {
		_ = q.InsertCheckResult(ctx, store.InsertCheckResultParams{CheckID: c.ID, CheckedAt: now.Add(-time.Duration(i+10) * time.Second), Status: "up"})
	}
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 != id2 {
		t.Fatalf("expected reopen, got new %d", id2)
	}
}

func TestReopenFlappingLowDownCreatesNew(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	setReopenMode(t, db, "flapping_only", 3600)
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 5*time.Minute)
	now := time.Now().UTC()
	for i := 0; i < 1; i++ {
		_ = q.InsertCheckResult(ctx, store.InsertCheckResultParams{CheckID: c.ID, CheckedAt: now.Add(-time.Duration(i) * time.Second), Status: "down"})
	}
	for i := 0; i < 5; i++ {
		_ = q.InsertCheckResult(ctx, store.InsertCheckResultParams{CheckID: c.ID, CheckedAt: now.Add(-time.Duration(i+1) * time.Minute), Status: "up"})
	}
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 == id2 {
		t.Fatal("expected new incident, got reopen")
	}
}

func TestReopenPerCheckOverrideBeatsGlobal(t *testing.T) {
	svc, q, db := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	setReopenMode(t, db, "always", 3600)
	if _, err := db.Exec("UPDATE checks SET reopen_mode = 'never' WHERE id = ?", c.ID); err != nil {
		t.Fatalf("override: %v", err)
	}
	c, _ = q.GetCheck(ctx, c.ID)
	id1, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	resolveAndBackdate(t, svc, db, ctx, id1, 1*time.Minute)
	id2, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto2: %v", err)
	}
	if id1 == id2 {
		t.Fatal("per-check 'never' should override global 'always'")
	}
}

func TestTransitionInvalidReturnsError(t *testing.T) {
	svc, q, _ := newTestService(t)
	ctx := context.Background()
	c := createCheck(t, q, "api")
	id, err := svc.CreateAutoFromCheckFailure(ctx, c)
	if err != nil {
		t.Fatalf("auto: %v", err)
	}
	// investigating → identified (ok) so we're in identified
	if err := svc.Transition(ctx, id, StatusIdentified, nil, ""); err != nil {
		t.Fatalf("to identified: %v", err)
	}
	// identified → investigating is invalid
	if err := svc.Transition(ctx, id, StatusInvestigating, nil, ""); err != ErrInvalidTransition {
		t.Fatalf("expected ErrInvalidTransition, got %v", err)
	}
	_ = q
}
