// SPDX-License-Identifier: AGPL-3.0-or-later
package incident

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"github.com/TRC-Loop/cairn/internal/store"
)

var ErrInvalidTransition = errors.New("invalid incident status transition")

// MaintenanceService is the narrow surface the incident service needs from the
// maintenance package. Declared here (not imported) to keep the dependency
// edge incident → maintenance one-way: the incident package owns the contract.
type MaintenanceService interface {
	IsCheckUnderMaintenance(ctx context.Context, checkID int64) (bool, error)
}

// Notifier is the narrow surface the incident service needs from the notifier
// package. Implementations dispatch to all channels associated with the given
// check IDs.
type Notifier interface {
	NotifyChecks(ctx context.Context, eventType string, eventID int64, payload NotifierPayload, checkIDs []int64) (int, error)
}

// NotifierPayload mirrors notifier.Payload without importing the notifier
// package, keeping the dependency direction clean.
type NotifierPayload struct {
	EventType string
	EventID   int64
	Subject   string
	Body      string
	Severity  string
	Links     []NotifierLink
	Timestamp time.Time
}

type NotifierLink struct {
	Label string
	URL   string
}

const (
	EventIncidentOpened   = "incident_opened"
	EventIncidentUpdated  = "incident_updated"
	EventIncidentResolved = "incident_resolved"
)

type Service struct {
	db          *sql.DB
	q           *store.Queries
	logger      *slog.Logger
	maintenance MaintenanceService
	notifier    Notifier
}

func NewService(db *sql.DB, q *store.Queries, logger *slog.Logger, maintenance MaintenanceService) *Service {
	return &Service{db: db, q: q, logger: logger, maintenance: maintenance}
}

func (s *Service) SetNotifier(n Notifier) { s.notifier = n }

type CreateIncidentInput struct {
	Title            string
	Severity         Severity
	InitialMessage   string
	AffectedCheckIDs []int64
	CreatedByUserID  int64
}

type PostUpdateInput struct {
	IncidentID   int64
	Message      string
	NewStatus    *Status
	PostedByUser int64
}

func (s *Service) CreateManual(ctx context.Context, in CreateIncidentInput) (store.Incident, error) {
	if in.Title == "" {
		return store.Incident{}, errors.New("incident title required")
	}
	if !in.Severity.Valid() {
		return store.Incident{}, fmt.Errorf("invalid severity %q", in.Severity)
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return store.Incident{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	qtx := s.q.WithTx(tx)

	now := time.Now().UTC()
	inc, err := qtx.CreateIncident(ctx, store.CreateIncidentParams{
		Title:             in.Title,
		Status:            string(StatusInvestigating),
		Severity:          string(in.Severity),
		StartedAt:         now,
		AutoCreated:       false,
		TriggeringCheckID: sql.NullInt64{},
		CreatedByUserID:   nullableUser(in.CreatedByUserID),
	})
	if err != nil {
		return store.Incident{}, fmt.Errorf("create incident: %w", err)
	}

	if in.InitialMessage != "" {
		if _, err := qtx.CreateIncidentUpdate(ctx, store.CreateIncidentUpdateParams{
			IncidentID:      inc.ID,
			Status:          inc.Status,
			Message:         in.InitialMessage,
			PostedByUserID:  nullableUser(in.CreatedByUserID),
			AutoGenerated:   false,
		}); err != nil {
			return store.Incident{}, fmt.Errorf("create initial update: %w", err)
		}
	}

	for _, id := range in.AffectedCheckIDs {
		if err := qtx.LinkCheckToIncident(ctx, store.LinkCheckToIncidentParams{
			IncidentID: inc.ID,
			CheckID:    id,
		}); err != nil {
			return store.Incident{}, fmt.Errorf("link check %d: %w", id, err)
		}
	}

	if err := tx.Commit(); err != nil {
		return store.Incident{}, fmt.Errorf("commit: %w", err)
	}
	s.notifyOpened(ctx, inc, in.AffectedCheckIDs, in.InitialMessage)
	return inc, nil
}

// CreateAutoFromCheckFailure returns the ID of an existing open incident for the
// given check, or creates a new auto-incident if none is open. Idempotent across
// concurrent failure ticks.
func (s *Service) CreateAutoFromCheckFailure(ctx context.Context, c store.Check) (int64, error) {
	// Existing open incident wins regardless of maintenance: a maintenance
	// window starting mid-incident must not orphan the caller's tracking ID.
	if existing, ok, err := s.FindOpenForCheck(ctx, c.ID); err != nil {
		return 0, err
	} else if ok {
		return existing.ID, nil
	}

	if s.maintenance != nil {
		underMaintenance, err := s.maintenance.IsCheckUnderMaintenance(ctx, c.ID)
		if err != nil {
			s.logger.Warn("maintenance check failed; proceeding with incident creation", "check_id", c.ID, "err", err)
		} else if underMaintenance {
			s.logger.Info("check is down but under maintenance; no incident", "check_id", c.ID, "check_name", c.Name)
			return 0, nil
		}
	}

	if id, reopened, err := s.tryReopenForCheck(ctx, c); err != nil {
		s.logger.Warn("reopen check failed; falling through to new incident", "check_id", c.ID, "err", err)
	} else if reopened {
		return id, nil
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return 0, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	qtx := s.q.WithTx(tx)

	now := time.Now().UTC()
	inc, err := qtx.CreateIncident(ctx, store.CreateIncidentParams{
		Title:             fmt.Sprintf("Outage: %s", c.Name),
		Status:            string(StatusInvestigating),
		Severity:          string(SeverityMajor),
		StartedAt:         now,
		AutoCreated:       true,
		TriggeringCheckID: sql.NullInt64{Int64: c.ID, Valid: true},
		CreatedByUserID:   sql.NullInt64{},
	})
	if err != nil {
		return 0, fmt.Errorf("create incident: %w", err)
	}

	if err := qtx.LinkCheckToIncident(ctx, store.LinkCheckToIncidentParams{
		IncidentID: inc.ID,
		CheckID:    c.ID,
	}); err != nil {
		return 0, fmt.Errorf("link check: %w", err)
	}

	if _, err := qtx.CreateIncidentUpdate(ctx, store.CreateIncidentUpdateParams{
		IncidentID:     inc.ID,
		Status:         string(StatusInvestigating),
		Message:        fmt.Sprintf("Cairn detected %s is down.", c.Name),
		PostedByUserID: sql.NullInt64{},
		AutoGenerated:  true,
	}); err != nil {
		return 0, fmt.Errorf("create initial update: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return 0, fmt.Errorf("commit: %w", err)
	}
	s.logger.Info("auto-incident created", "incident_id", inc.ID, "check_id", c.ID, "check_name", c.Name)
	s.notifyOpened(ctx, inc, []int64{c.ID}, fmt.Sprintf("Cairn detected %s is down.", c.Name))
	return inc.ID, nil
}

func (s *Service) PostUpdate(ctx context.Context, in PostUpdateInput) (store.IncidentUpdate, error) {
	if in.Message == "" {
		return store.IncidentUpdate{}, errors.New("update message required")
	}
	inc, err := s.q.GetIncident(ctx, in.IncidentID)
	if err != nil {
		return store.IncidentUpdate{}, fmt.Errorf("get incident: %w", err)
	}

	targetStatus := Status(inc.Status)
	if in.NewStatus != nil {
		targetStatus = *in.NewStatus
		if !ValidTransition(Status(inc.Status), targetStatus) {
			return store.IncidentUpdate{}, ErrInvalidTransition
		}
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return store.IncidentUpdate{}, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	qtx := s.q.WithTx(tx)

	if in.NewStatus != nil && Status(inc.Status) != targetStatus {
		if err := s.applyTransition(ctx, qtx, inc, targetStatus); err != nil {
			return store.IncidentUpdate{}, err
		}
	}

	upd, err := qtx.CreateIncidentUpdate(ctx, store.CreateIncidentUpdateParams{
		IncidentID:     in.IncidentID,
		Status:         string(targetStatus),
		Message:        in.Message,
		PostedByUserID: nullableUser(in.PostedByUser),
		AutoGenerated:  false,
	})
	if err != nil {
		return store.IncidentUpdate{}, fmt.Errorf("create update: %w", err)
	}

	if err := tx.Commit(); err != nil {
		return store.IncidentUpdate{}, fmt.Errorf("commit: %w", err)
	}
	s.notifyUpdate(ctx, in.IncidentID, targetStatus, in.Message)
	return upd, nil
}

func (s *Service) Transition(ctx context.Context, incidentID int64, to Status, userID *int64, message string) error {
	if !to.Valid() {
		return fmt.Errorf("invalid target status %q", to)
	}
	inc, err := s.q.GetIncident(ctx, incidentID)
	if err != nil {
		return fmt.Errorf("get incident: %w", err)
	}
	from := Status(inc.Status)
	if !ValidTransition(from, to) {
		return ErrInvalidTransition
	}
	if from == StatusResolved && to == StatusInvestigating {
		s.logger.Warn("incident reopened", "incident_id", incidentID)
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	qtx := s.q.WithTx(tx)

	if from != to {
		if err := s.applyTransition(ctx, qtx, inc, to); err != nil {
			return err
		}
	}

	var posted sql.NullInt64
	if userID != nil {
		posted = sql.NullInt64{Int64: *userID, Valid: true}
	}
	autoGen := userID == nil
	if message != "" {
		if _, err := qtx.CreateIncidentUpdate(ctx, store.CreateIncidentUpdateParams{
			IncidentID:     incidentID,
			Status:         string(to),
			Message:        message,
			PostedByUserID: posted,
			AutoGenerated:  autoGen,
		}); err != nil {
			return fmt.Errorf("create update: %w", err)
		}
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}
	s.notifyUpdate(ctx, incidentID, to, message)
	return nil
}

// tryReopenForCheck inspects the most recent resolved incident for the check
// and reopens it if window+mode rules apply. Returns (incidentID, true, nil)
// when a reopen happened, (0, false, nil) when caller should fall through to
// new-incident creation.
func (s *Service) tryReopenForCheck(ctx context.Context, c store.Check) (int64, bool, error) {
	prev, err := s.q.GetMostRecentResolvedIncidentForCheck(ctx, c.ID)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return 0, false, nil
		}
		return 0, false, fmt.Errorf("get most recent resolved: %w", err)
	}
	if !prev.ResolvedAt.Valid {
		return 0, false, nil
	}

	windowSec, mode := s.resolveReopenSettings(ctx, c)
	if mode == "never" {
		return 0, false, nil
	}
	now := time.Now().UTC()
	if now.Sub(prev.ResolvedAt.Time) > time.Duration(windowSec)*time.Second {
		return 0, false, nil
	}

	if mode == "flapping_only" {
		rows, err := s.q.CountResultsByStatusInRange(ctx, store.CountResultsByStatusInRangeParams{
			CheckID:     c.ID,
			CheckedAt:   prev.ResolvedAt.Time,
			CheckedAt_2: now,
		})
		if err != nil {
			return 0, false, fmt.Errorf("count results: %w", err)
		}
		var down, total int64
		for _, r := range rows {
			total += r.Count
			if r.Status == "down" {
				down += r.Count
			}
		}
		if total == 0 || float64(down)/float64(total) <= 0.5 {
			return 0, false, nil
		}
	}

	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return 0, false, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()
	qtx := s.q.WithTx(tx)

	if err := qtx.UpdateIncidentStatus(ctx, store.UpdateIncidentStatusParams{
		Status:     string(StatusInvestigating),
		ResolvedAt: sql.NullTime{},
		ID:         prev.ID,
	}); err != nil {
		return 0, false, fmt.Errorf("update status: %w", err)
	}
	msg := fmt.Sprintf("Cairn detected %s has failed again — reopening incident.", c.Name)
	if _, err := qtx.CreateIncidentUpdate(ctx, store.CreateIncidentUpdateParams{
		IncidentID:     prev.ID,
		Status:         string(StatusInvestigating),
		Message:        msg,
		PostedByUserID: sql.NullInt64{},
		AutoGenerated:  true,
	}); err != nil {
		return 0, false, fmt.Errorf("create update: %w", err)
	}
	if err := tx.Commit(); err != nil {
		return 0, false, fmt.Errorf("commit: %w", err)
	}
	s.logger.Info("incident reopened", "incident_id", prev.ID, "check_id", c.ID, "mode", mode)
	s.notifyUpdate(ctx, prev.ID, StatusInvestigating, msg)
	return prev.ID, true, nil
}

func (s *Service) resolveReopenSettings(ctx context.Context, c store.Check) (int64, string) {
	windowSec := int64(3600)
	mode := "always"
	if settings, err := s.q.GetSystemSettings(ctx); err == nil {
		windowSec = settings.IncidentReopenWindowSeconds
		mode = settings.IncidentReopenMode
	}
	if c.ReopenWindowSeconds.Valid {
		windowSec = c.ReopenWindowSeconds.Int64
	}
	if c.ReopenMode.Valid && c.ReopenMode.String != "" {
		mode = c.ReopenMode.String
	}
	return windowSec, mode
}

func (s *Service) FindOpenForCheck(ctx context.Context, checkID int64) (store.Incident, bool, error) {
	incs, err := s.q.ListIncidentsForCheck(ctx, store.ListIncidentsForCheckParams{
		CheckID: checkID,
		Limit:   20,
	})
	if err != nil {
		return store.Incident{}, false, fmt.Errorf("list incidents for check: %w", err)
	}
	for _, inc := range incs {
		if inc.Status != string(StatusResolved) {
			return inc, true, nil
		}
	}
	return store.Incident{}, false, nil
}

func (s *Service) applyTransition(ctx context.Context, qtx *store.Queries, inc store.Incident, to Status) error {
	var resolvedAt sql.NullTime
	if to == StatusResolved {
		resolvedAt = sql.NullTime{Time: time.Now().UTC(), Valid: true}
	} else if inc.ResolvedAt.Valid {
		// Reopening from resolved: clear resolved_at.
		resolvedAt = sql.NullTime{}
	} else {
		resolvedAt = inc.ResolvedAt
	}
	if err := qtx.UpdateIncidentStatus(ctx, store.UpdateIncidentStatusParams{
		Status:     string(to),
		ResolvedAt: resolvedAt,
		ID:         inc.ID,
	}); err != nil {
		return fmt.Errorf("update incident status: %w", err)
	}
	return nil
}

// notifyOpened dispatches an incident_opened notification. Suppression for
// active maintenance is delegated to the dispatcher.
func (s *Service) notifyOpened(ctx context.Context, inc store.Incident, checkIDs []int64, message string) {
	if s.notifier == nil || len(checkIDs) == 0 {
		return
	}
	body := message
	if body == "" {
		body = fmt.Sprintf("Incident opened: %s", inc.Title)
	}
	payload := NotifierPayload{
		EventType: EventIncidentOpened,
		EventID:   inc.ID,
		Subject:   inc.Title,
		Body:      body,
		Severity:  inc.Severity,
		Timestamp: time.Now().UTC(),
	}
	if _, err := s.notifier.NotifyChecks(ctx, EventIncidentOpened, inc.ID, payload, checkIDs); err != nil {
		s.logger.Error("notify incident_opened failed", "incident_id", inc.ID, "err", err)
	}
}

// notifyUpdate dispatches incident_updated, or incident_resolved if the
// incident has been transitioned to resolved. checks are looked up via the
// incident_affected_checks table so we always notify the same recipients as
// the original opened event. Resolution notifications are NOT suppressed by
// maintenance — operators want to know things recovered.
func (s *Service) notifyUpdate(ctx context.Context, incidentID int64, status Status, message string) {
	if s.notifier == nil {
		return
	}
	checkIDs, err := s.q.ListAffectedCheckIDsForIncident(ctx, incidentID)
	if err != nil {
		s.logger.Error("list affected checks for notify failed", "incident_id", incidentID, "err", err)
		return
	}
	if len(checkIDs) == 0 {
		return
	}
	inc, err := s.q.GetIncident(ctx, incidentID)
	if err != nil {
		s.logger.Error("get incident for notify failed", "incident_id", incidentID, "err", err)
		return
	}
	eventType := EventIncidentUpdated
	severity := inc.Severity
	if status == StatusResolved {
		eventType = EventIncidentResolved
		severity = "info"
	}
	body := message
	if body == "" {
		if status == StatusResolved {
			body = fmt.Sprintf("Incident resolved: %s", inc.Title)
		} else {
			body = fmt.Sprintf("Incident update: %s", inc.Title)
		}
	}
	payload := NotifierPayload{
		EventType: eventType,
		EventID:   inc.ID,
		Subject:   inc.Title,
		Body:      body,
		Severity:  severity,
		Timestamp: time.Now().UTC(),
	}
	if _, err := s.notifier.NotifyChecks(ctx, eventType, inc.ID, payload, checkIDs); err != nil {
		s.logger.Error("notify incident update failed", "incident_id", inc.ID, "event", eventType, "err", err)
	}
}

func nullableUser(id int64) sql.NullInt64 {
	if id <= 0 {
		return sql.NullInt64{}
	}
	return sql.NullInt64{Int64: id, Valid: true}
}
