// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: check_notification_channels.sql

package store

import (
	"context"
)

const clearChannelsForCheck = `-- name: ClearChannelsForCheck :exec
DELETE FROM check_notification_channels WHERE check_id = ?
`

func (q *Queries) ClearChannelsForCheck(ctx context.Context, checkID int64) error {
	_, err := q.db.ExecContext(ctx, clearChannelsForCheck, checkID)
	return err
}

const linkCheckToChannel = `-- name: LinkCheckToChannel :exec
INSERT OR IGNORE INTO check_notification_channels (check_id, channel_id)
VALUES (?, ?)
`

type LinkCheckToChannelParams struct {
	CheckID   int64 `json:"check_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) LinkCheckToChannel(ctx context.Context, arg LinkCheckToChannelParams) error {
	_, err := q.db.ExecContext(ctx, linkCheckToChannel, arg.CheckID, arg.ChannelID)
	return err
}

const listChannelRowsForCheck = `-- name: ListChannelRowsForCheck :many
SELECT nc.id, nc.name, nc.type, nc.enabled, nc.config_json, nc.retry_max, nc.retry_backoff_seconds, nc.created_at, nc.updated_at
FROM check_notification_channels cnc
JOIN notification_channels nc ON nc.id = cnc.channel_id
WHERE cnc.check_id = ?
ORDER BY nc.name ASC
`

func (q *Queries) ListChannelRowsForCheck(ctx context.Context, checkID int64) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listChannelRowsForCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.ConfigJson,
			&i.RetryMax,
			&i.RetryBackoffSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChannelsForCheck = `-- name: ListChannelsForCheck :many
SELECT channel_id FROM check_notification_channels
WHERE check_id = ?
ORDER BY channel_id ASC
`

func (q *Queries) ListChannelsForCheck(ctx context.Context, checkID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChannelsForCheck, checkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var channel_id int64
		if err := rows.Scan(&channel_id); err != nil {
			return nil, err
		}
		items = append(items, channel_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecksForChannel = `-- name: ListChecksForChannel :many
SELECT check_id FROM check_notification_channels
WHERE channel_id = ?
ORDER BY check_id ASC
`

func (q *Queries) ListChecksForChannel(ctx context.Context, channelID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listChecksForChannel, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var check_id int64
		if err := rows.Scan(&check_id); err != nil {
			return nil, err
		}
		items = append(items, check_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkCheckFromChannel = `-- name: UnlinkCheckFromChannel :exec
DELETE FROM check_notification_channels
WHERE check_id = ? AND channel_id = ?
`

type UnlinkCheckFromChannelParams struct {
	CheckID   int64 `json:"check_id"`
	ChannelID int64 `json:"channel_id"`
}

func (q *Queries) UnlinkCheckFromChannel(ctx context.Context, arg UnlinkCheckFromChannelParams) error {
	_, err := q.db.ExecContext(ctx, unlinkCheckFromChannel, arg.CheckID, arg.ChannelID)
	return err
}
