// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checks.sql

package store

import (
	"context"
	"database/sql"
)

const countChecksByStatus = `-- name: CountChecksByStatus :many
SELECT last_status AS status, COUNT(*) AS count
FROM checks
WHERE enabled = 1
GROUP BY last_status
`

type CountChecksByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountChecksByStatus(ctx context.Context) ([]CountChecksByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countChecksByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountChecksByStatusRow{}
	for rows.Next() {
		var i CountChecksByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createCheck = `-- name: CreateCheck :one
INSERT INTO checks (
    name, type, enabled, interval_seconds, timeout_seconds, retries,
    failure_threshold, recovery_threshold, config_json, component_id,
    reopen_window_seconds, reopen_mode
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode
`

type CreateCheckParams struct {
	Name                string         `json:"name"`
	Type                string         `json:"type"`
	Enabled             bool           `json:"enabled"`
	IntervalSeconds     int64          `json:"interval_seconds"`
	TimeoutSeconds      int64          `json:"timeout_seconds"`
	Retries             int64          `json:"retries"`
	FailureThreshold    int64          `json:"failure_threshold"`
	RecoveryThreshold   int64          `json:"recovery_threshold"`
	ConfigJson          string         `json:"config_json"`
	ComponentID         sql.NullInt64  `json:"component_id"`
	ReopenWindowSeconds sql.NullInt64  `json:"reopen_window_seconds"`
	ReopenMode          sql.NullString `json:"reopen_mode"`
}

func (q *Queries) CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error) {
	row := q.db.QueryRowContext(ctx, createCheck,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Retries,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
		arg.ConfigJson,
		arg.ComponentID,
		arg.ReopenWindowSeconds,
		arg.ReopenMode,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.ConfigJson,
		&i.ComponentID,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastCheckedAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.ReopenWindowSeconds,
		&i.ReopenMode,
	)
	return i, err
}

const deleteCheck = `-- name: DeleteCheck :exec
DELETE FROM checks WHERE id = ?
`

func (q *Queries) DeleteCheck(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCheck, id)
	return err
}

const getCheck = `-- name: GetCheck :one
SELECT id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode FROM checks WHERE id = ? LIMIT 1
`

func (q *Queries) GetCheck(ctx context.Context, id int64) (Check, error) {
	row := q.db.QueryRowContext(ctx, getCheck, id)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.ConfigJson,
		&i.ComponentID,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastCheckedAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.ReopenWindowSeconds,
		&i.ReopenMode,
	)
	return i, err
}

const getCheckByPushToken = `-- name: GetCheckByPushToken :one
SELECT id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode FROM checks WHERE push_token = ? LIMIT 1
`

func (q *Queries) GetCheckByPushToken(ctx context.Context, pushToken sql.NullString) (Check, error) {
	row := q.db.QueryRowContext(ctx, getCheckByPushToken, pushToken)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.ConfigJson,
		&i.ComponentID,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastCheckedAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.ReopenWindowSeconds,
		&i.ReopenMode,
	)
	return i, err
}

const listChecks = `-- name: ListChecks :many
SELECT id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode FROM checks ORDER BY name ASC
`

func (q *Queries) ListChecks(ctx context.Context) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledChecksDue = `-- name: ListEnabledChecksDue :many
SELECT id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode FROM checks
WHERE enabled = 1
  AND type != 'push'
  AND (last_checked_at IS NULL
       OR last_checked_at <= datetime('now', printf('-%d seconds', interval_seconds)))
ORDER BY last_checked_at ASC NULLS FIRST
`

func (q *Queries) ListEnabledChecksDue(ctx context.Context) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledChecksDue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledPushChecks = `-- name: ListEnabledPushChecks :many
SELECT id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode FROM checks
WHERE enabled = 1
  AND type = 'push'
ORDER BY id ASC
`

func (q *Queries) ListEnabledPushChecks(ctx context.Context) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledPushChecks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCheckPushToken = `-- name: SetCheckPushToken :exec
UPDATE checks SET push_token = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type SetCheckPushTokenParams struct {
	PushToken sql.NullString `json:"push_token"`
	ID        int64          `json:"id"`
}

func (q *Queries) SetCheckPushToken(ctx context.Context, arg SetCheckPushTokenParams) error {
	_, err := q.db.ExecContext(ctx, setCheckPushToken, arg.PushToken, arg.ID)
	return err
}

const updateCheck = `-- name: UpdateCheck :one
UPDATE checks
SET name                  = ?,
    type                  = ?,
    enabled               = ?,
    interval_seconds      = ?,
    timeout_seconds       = ?,
    retries               = ?,
    failure_threshold     = ?,
    recovery_threshold    = ?,
    config_json           = ?,
    component_id          = ?,
    reopen_window_seconds = ?,
    reopen_mode           = ?,
    updated_at            = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, enabled, interval_seconds, timeout_seconds, retries, failure_threshold, recovery_threshold, config_json, component_id, last_status, last_latency_ms, last_checked_at, consecutive_failures, consecutive_successes, created_at, updated_at, push_token, reopen_window_seconds, reopen_mode
`

type UpdateCheckParams struct {
	Name                string         `json:"name"`
	Type                string         `json:"type"`
	Enabled             bool           `json:"enabled"`
	IntervalSeconds     int64          `json:"interval_seconds"`
	TimeoutSeconds      int64          `json:"timeout_seconds"`
	Retries             int64          `json:"retries"`
	FailureThreshold    int64          `json:"failure_threshold"`
	RecoveryThreshold   int64          `json:"recovery_threshold"`
	ConfigJson          string         `json:"config_json"`
	ComponentID         sql.NullInt64  `json:"component_id"`
	ReopenWindowSeconds sql.NullInt64  `json:"reopen_window_seconds"`
	ReopenMode          sql.NullString `json:"reopen_mode"`
	ID                  int64          `json:"id"`
}

func (q *Queries) UpdateCheck(ctx context.Context, arg UpdateCheckParams) (Check, error) {
	row := q.db.QueryRowContext(ctx, updateCheck,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.IntervalSeconds,
		arg.TimeoutSeconds,
		arg.Retries,
		arg.FailureThreshold,
		arg.RecoveryThreshold,
		arg.ConfigJson,
		arg.ComponentID,
		arg.ReopenWindowSeconds,
		arg.ReopenMode,
		arg.ID,
	)
	var i Check
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.IntervalSeconds,
		&i.TimeoutSeconds,
		&i.Retries,
		&i.FailureThreshold,
		&i.RecoveryThreshold,
		&i.ConfigJson,
		&i.ComponentID,
		&i.LastStatus,
		&i.LastLatencyMs,
		&i.LastCheckedAt,
		&i.ConsecutiveFailures,
		&i.ConsecutiveSuccesses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.PushToken,
		&i.ReopenWindowSeconds,
		&i.ReopenMode,
	)
	return i, err
}

const updateCheckStatus = `-- name: UpdateCheckStatus :exec
UPDATE checks
SET last_status           = ?,
    last_latency_ms       = ?,
    last_checked_at       = ?,
    consecutive_failures  = ?,
    consecutive_successes = ?,
    updated_at            = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCheckStatusParams struct {
	LastStatus           string        `json:"last_status"`
	LastLatencyMs        sql.NullInt64 `json:"last_latency_ms"`
	LastCheckedAt        sql.NullTime  `json:"last_checked_at"`
	ConsecutiveFailures  int64         `json:"consecutive_failures"`
	ConsecutiveSuccesses int64         `json:"consecutive_successes"`
	ID                   int64         `json:"id"`
}

func (q *Queries) UpdateCheckStatus(ctx context.Context, arg UpdateCheckStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCheckStatus,
		arg.LastStatus,
		arg.LastLatencyMs,
		arg.LastCheckedAt,
		arg.ConsecutiveFailures,
		arg.ConsecutiveSuccesses,
		arg.ID,
	)
	return err
}
