// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: components.sql

package store

import (
	"context"
	"database/sql"
)

const countChecksForComponent = `-- name: CountChecksForComponent :one
SELECT COUNT(*) AS count FROM checks WHERE component_id = ?
`

func (q *Queries) CountChecksForComponent(ctx context.Context, componentID sql.NullInt64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChecksForComponent, componentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createComponent = `-- name: CreateComponent :one
INSERT INTO components (name, description, display_order)
VALUES (?, ?, ?)
RETURNING id, name, description, display_order, created_at, updated_at
`

type CreateComponentParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
}

func (q *Queries) CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error) {
	row := q.db.QueryRowContext(ctx, createComponent, arg.Name, arg.Description, arg.DisplayOrder)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComponent = `-- name: DeleteComponent :exec
DELETE FROM components WHERE id = ?
`

func (q *Queries) DeleteComponent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteComponent, id)
	return err
}

const getComponent = `-- name: GetComponent :one
SELECT id, name, description, display_order, created_at, updated_at FROM components WHERE id = ? LIMIT 1
`

func (q *Queries) GetComponent(ctx context.Context, id int64) (Component, error) {
	row := q.db.QueryRowContext(ctx, getComponent, id)
	var i Component
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChecksForComponent = `-- name: ListChecksForComponent :many
SELECT checks.id, checks.name, checks.type, checks.enabled, checks.interval_seconds, checks.timeout_seconds, checks.retries, checks.failure_threshold, checks.recovery_threshold, checks.config_json, checks.component_id, checks.last_status, checks.last_latency_ms, checks.last_checked_at, checks.consecutive_failures, checks.consecutive_successes, checks.created_at, checks.updated_at, checks.push_token, checks.reopen_window_seconds, checks.reopen_mode FROM checks
WHERE checks.component_id = ?
ORDER BY checks.name ASC
`

func (q *Queries) ListChecksForComponent(ctx context.Context, componentID sql.NullInt64) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksForComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponents = `-- name: ListComponents :many
SELECT id, name, description, display_order, created_at, updated_at FROM components ORDER BY display_order ASC, name ASC
`

func (q *Queries) ListComponents(ctx context.Context) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listComponents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComponent = `-- name: UpdateComponent :exec
UPDATE components
SET name          = ?,
    description   = ?,
    display_order = ?,
    updated_at    = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateComponentParams struct {
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateComponent(ctx context.Context, arg UpdateComponentParams) error {
	_, err := q.db.ExecContext(ctx, updateComponent,
		arg.Name,
		arg.Description,
		arg.DisplayOrder,
		arg.ID,
	)
	return err
}
