// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package store

import (
	"context"
	"time"
)

const dashboardUptime24h = `-- name: DashboardUptime24h :one
SELECT
  CAST(COALESCE(SUM(CASE WHEN status = 'up' THEN 1 ELSE 0 END), 0) AS INTEGER) AS up_count,
  CAST(COALESCE(COUNT(*), 0) AS INTEGER) AS total_count
FROM check_results
WHERE checked_at >= ?
`

type DashboardUptime24hRow struct {
	UpCount    int64 `json:"up_count"`
	TotalCount int64 `json:"total_count"`
}

func (q *Queries) DashboardUptime24h(ctx context.Context, checkedAt time.Time) (DashboardUptime24hRow, error) {
	row := q.db.QueryRowContext(ctx, dashboardUptime24h, checkedAt)
	var i DashboardUptime24hRow
	err := row.Scan(&i.UpCount, &i.TotalCount)
	return i, err
}

const listIncidentsSince = `-- name: ListIncidentsSince :many
SELECT id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at FROM incidents WHERE started_at >= ? ORDER BY started_at DESC
`

func (q *Queries) ListIncidentsSince(ctx context.Context, startedAt time.Time) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentsSince, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AutoCreated,
			&i.TriggeringCheckID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
