// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: footer_elements.sql

package store

import (
	"context"
	"database/sql"
)

const createFooterElement = `-- name: CreateFooterElement :one
INSERT INTO status_page_footer_elements (
    status_page_id, element_type, label, url, open_in_new_tab, display_order
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, status_page_id, element_type, label, url, open_in_new_tab, display_order, created_at
`

type CreateFooterElementParams struct {
	StatusPageID int64          `json:"status_page_id"`
	ElementType  string         `json:"element_type"`
	Label        sql.NullString `json:"label"`
	Url          sql.NullString `json:"url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	DisplayOrder int64          `json:"display_order"`
}

func (q *Queries) CreateFooterElement(ctx context.Context, arg CreateFooterElementParams) (StatusPageFooterElement, error) {
	row := q.db.QueryRowContext(ctx, createFooterElement,
		arg.StatusPageID,
		arg.ElementType,
		arg.Label,
		arg.Url,
		arg.OpenInNewTab,
		arg.DisplayOrder,
	)
	var i StatusPageFooterElement
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.ElementType,
		&i.Label,
		&i.Url,
		&i.OpenInNewTab,
		&i.DisplayOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFooterElement = `-- name: DeleteFooterElement :exec
DELETE FROM status_page_footer_elements WHERE id = ?
`

func (q *Queries) DeleteFooterElement(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFooterElement, id)
	return err
}

const deleteFooterElementsForPage = `-- name: DeleteFooterElementsForPage :exec
DELETE FROM status_page_footer_elements WHERE status_page_id = ?
`

func (q *Queries) DeleteFooterElementsForPage(ctx context.Context, statusPageID int64) error {
	_, err := q.db.ExecContext(ctx, deleteFooterElementsForPage, statusPageID)
	return err
}

const listFooterElements = `-- name: ListFooterElements :many
SELECT id, status_page_id, element_type, label, url, open_in_new_tab, display_order, created_at FROM status_page_footer_elements
WHERE status_page_id = ?
ORDER BY display_order ASC, id ASC
`

func (q *Queries) ListFooterElements(ctx context.Context, statusPageID int64) ([]StatusPageFooterElement, error) {
	rows, err := q.db.QueryContext(ctx, listFooterElements, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageFooterElement{}
	for rows.Next() {
		var i StatusPageFooterElement
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.ElementType,
			&i.Label,
			&i.Url,
			&i.OpenInNewTab,
			&i.DisplayOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFooterElement = `-- name: UpdateFooterElement :exec
UPDATE status_page_footer_elements
SET element_type    = ?,
    label           = ?,
    url             = ?,
    open_in_new_tab = ?,
    display_order   = ?
WHERE id = ?
`

type UpdateFooterElementParams struct {
	ElementType  string         `json:"element_type"`
	Label        sql.NullString `json:"label"`
	Url          sql.NullString `json:"url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	DisplayOrder int64          `json:"display_order"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateFooterElement(ctx context.Context, arg UpdateFooterElementParams) error {
	_, err := q.db.ExecContext(ctx, updateFooterElement,
		arg.ElementType,
		arg.Label,
		arg.Url,
		arg.OpenInNewTab,
		arg.DisplayOrder,
		arg.ID,
	)
	return err
}
