// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_affected_checks.sql

package store

import (
	"context"
)

const linkCheckToIncident = `-- name: LinkCheckToIncident :exec
INSERT OR IGNORE INTO incident_affected_checks (incident_id, check_id)
VALUES (?, ?)
`

type LinkCheckToIncidentParams struct {
	IncidentID int64 `json:"incident_id"`
	CheckID    int64 `json:"check_id"`
}

func (q *Queries) LinkCheckToIncident(ctx context.Context, arg LinkCheckToIncidentParams) error {
	_, err := q.db.ExecContext(ctx, linkCheckToIncident, arg.IncidentID, arg.CheckID)
	return err
}

const listAffectedCheckIDsForIncident = `-- name: ListAffectedCheckIDsForIncident :many
SELECT check_id FROM incident_affected_checks
WHERE incident_id = ?
`

func (q *Queries) ListAffectedCheckIDsForIncident(ctx context.Context, incidentID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedCheckIDsForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var check_id int64
		if err := rows.Scan(&check_id); err != nil {
			return nil, err
		}
		items = append(items, check_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChecksForIncident = `-- name: ListChecksForIncident :many
SELECT c.id, c.name, c.type, c.enabled, c.interval_seconds, c.timeout_seconds, c.retries, c.failure_threshold, c.recovery_threshold, c.config_json, c.component_id, c.last_status, c.last_latency_ms, c.last_checked_at, c.consecutive_failures, c.consecutive_successes, c.created_at, c.updated_at, c.push_token, c.reopen_window_seconds, c.reopen_mode
FROM checks c
JOIN incident_affected_checks iac ON iac.check_id = c.id
WHERE iac.incident_id = ?
ORDER BY c.name ASC
`

func (q *Queries) ListChecksForIncident(ctx context.Context, incidentID int64) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listChecksForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidentsForCheck = `-- name: ListIncidentsForCheck :many
SELECT i.id, i.title, i.status, i.severity, i.started_at, i.resolved_at, i.auto_created, i.triggering_check_id, i.created_by_user_id, i.created_at, i.updated_at
FROM incidents i
JOIN incident_affected_checks iac ON iac.incident_id = i.id
WHERE iac.check_id = ?
ORDER BY i.started_at DESC
LIMIT ?
`

type ListIncidentsForCheckParams struct {
	CheckID int64 `json:"check_id"`
	Limit   int64 `json:"limit"`
}

func (q *Queries) ListIncidentsForCheck(ctx context.Context, arg ListIncidentsForCheckParams) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listIncidentsForCheck, arg.CheckID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AutoCreated,
			&i.TriggeringCheckID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkCheckFromIncident = `-- name: UnlinkCheckFromIncident :exec
DELETE FROM incident_affected_checks
WHERE incident_id = ? AND check_id = ?
`

type UnlinkCheckFromIncidentParams struct {
	IncidentID int64 `json:"incident_id"`
	CheckID    int64 `json:"check_id"`
}

func (q *Queries) UnlinkCheckFromIncident(ctx context.Context, arg UnlinkCheckFromIncidentParams) error {
	_, err := q.db.ExecContext(ctx, unlinkCheckFromIncident, arg.IncidentID, arg.CheckID)
	return err
}
