// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incidents.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createIncident = `-- name: CreateIncident :one
INSERT INTO incidents (
    title, status, severity, started_at, auto_created, triggering_check_id, created_by_user_id
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at
`

type CreateIncidentParams struct {
	Title             string        `json:"title"`
	Status            string        `json:"status"`
	Severity          string        `json:"severity"`
	StartedAt         time.Time     `json:"started_at"`
	AutoCreated       bool          `json:"auto_created"`
	TriggeringCheckID sql.NullInt64 `json:"triggering_check_id"`
	CreatedByUserID   sql.NullInt64 `json:"created_by_user_id"`
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error) {
	row := q.db.QueryRowContext(ctx, createIncident,
		arg.Title,
		arg.Status,
		arg.Severity,
		arg.StartedAt,
		arg.AutoCreated,
		arg.TriggeringCheckID,
		arg.CreatedByUserID,
	)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AutoCreated,
		&i.TriggeringCheckID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncident = `-- name: DeleteIncident :exec
DELETE FROM incidents WHERE id = ?
`

func (q *Queries) DeleteIncident(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteIncident, id)
	return err
}

const getIncident = `-- name: GetIncident :one
SELECT id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at FROM incidents WHERE id = ? LIMIT 1
`

func (q *Queries) GetIncident(ctx context.Context, id int64) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getIncident, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AutoCreated,
		&i.TriggeringCheckID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMostRecentResolvedIncidentForCheck = `-- name: GetMostRecentResolvedIncidentForCheck :one
SELECT i.id, i.title, i.status, i.severity, i.started_at, i.resolved_at, i.auto_created, i.triggering_check_id, i.created_by_user_id, i.created_at, i.updated_at
FROM incidents i
JOIN incident_affected_checks iac ON iac.incident_id = i.id
WHERE iac.check_id = ?
  AND i.status = 'resolved'
  AND i.resolved_at IS NOT NULL
ORDER BY i.resolved_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentResolvedIncidentForCheck(ctx context.Context, checkID int64) (Incident, error) {
	row := q.db.QueryRowContext(ctx, getMostRecentResolvedIncidentForCheck, checkID)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Status,
		&i.Severity,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.AutoCreated,
		&i.TriggeringCheckID,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveIncidents = `-- name: ListActiveIncidents :many
SELECT id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at FROM incidents
WHERE status != 'resolved'
ORDER BY started_at DESC
`

func (q *Queries) ListActiveIncidents(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listActiveIncidents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AutoCreated,
			&i.TriggeringCheckID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at FROM incidents
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListIncidentsParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listIncidents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AutoCreated,
			&i.TriggeringCheckID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentResolvedIncidents = `-- name: ListRecentResolvedIncidents :many
SELECT id, title, status, severity, started_at, resolved_at, auto_created, triggering_check_id, created_by_user_id, created_at, updated_at FROM incidents
WHERE status = 'resolved'
ORDER BY resolved_at DESC
LIMIT ?
`

func (q *Queries) ListRecentResolvedIncidents(ctx context.Context, limit int64) ([]Incident, error) {
	rows, err := q.db.QueryContext(ctx, listRecentResolvedIncidents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Incident{}
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Severity,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.AutoCreated,
			&i.TriggeringCheckID,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIncidentMetadata = `-- name: UpdateIncidentMetadata :exec
UPDATE incidents
SET title      = ?,
    severity   = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateIncidentMetadataParams struct {
	Title    string `json:"title"`
	Severity string `json:"severity"`
	ID       int64  `json:"id"`
}

func (q *Queries) UpdateIncidentMetadata(ctx context.Context, arg UpdateIncidentMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateIncidentMetadata, arg.Title, arg.Severity, arg.ID)
	return err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :exec
UPDATE incidents
SET status      = ?,
    resolved_at = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateIncidentStatusParams struct {
	Status     string       `json:"status"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
	ID         int64        `json:"id"`
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIncidentStatus, arg.Status, arg.ResolvedAt, arg.ID)
	return err
}
