// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: incident_updates.sql

package store

import (
	"context"
	"database/sql"
)

const createIncidentUpdate = `-- name: CreateIncidentUpdate :one
INSERT INTO incident_updates (
    incident_id, status, message, posted_by_user_id, auto_generated
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, incident_id, status, message, posted_by_user_id, auto_generated, created_at
`

type CreateIncidentUpdateParams struct {
	IncidentID     int64         `json:"incident_id"`
	Status         string        `json:"status"`
	Message        string        `json:"message"`
	PostedByUserID sql.NullInt64 `json:"posted_by_user_id"`
	AutoGenerated  bool          `json:"auto_generated"`
}

func (q *Queries) CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) (IncidentUpdate, error) {
	row := q.db.QueryRowContext(ctx, createIncidentUpdate,
		arg.IncidentID,
		arg.Status,
		arg.Message,
		arg.PostedByUserID,
		arg.AutoGenerated,
	)
	var i IncidentUpdate
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.Status,
		&i.Message,
		&i.PostedByUserID,
		&i.AutoGenerated,
		&i.CreatedAt,
	)
	return i, err
}

const listUpdatesForIncident = `-- name: ListUpdatesForIncident :many
SELECT id, incident_id, status, message, posted_by_user_id, auto_generated, created_at FROM incident_updates
WHERE incident_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListUpdatesForIncident(ctx context.Context, incidentID int64) ([]IncidentUpdate, error) {
	rows, err := q.db.QueryContext(ctx, listUpdatesForIncident, incidentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IncidentUpdate{}
	for rows.Next() {
		var i IncidentUpdate
		if err := rows.Scan(
			&i.ID,
			&i.IncidentID,
			&i.Status,
			&i.Message,
			&i.PostedByUserID,
			&i.AutoGenerated,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
