// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const autoCompleteDueMaintenance = `-- name: AutoCompleteDueMaintenance :exec
UPDATE maintenance_windows
SET state = 'completed', updated_at = CURRENT_TIMESTAMP
WHERE state = 'in_progress' AND ends_at <= datetime('now')
`

func (q *Queries) AutoCompleteDueMaintenance(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, autoCompleteDueMaintenance)
	return err
}

const autoStartDueMaintenance = `-- name: AutoStartDueMaintenance :exec
UPDATE maintenance_windows
SET state = 'in_progress', updated_at = CURRENT_TIMESTAMP
WHERE state = 'scheduled' AND starts_at <= datetime('now')
`

func (q *Queries) AutoStartDueMaintenance(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, autoStartDueMaintenance)
	return err
}

const cancelMaintenance = `-- name: CancelMaintenance :execrows
UPDATE maintenance_windows
SET state = 'cancelled', updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND state = 'scheduled'
`

func (q *Queries) CancelMaintenance(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelMaintenance, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const countMaintenanceAll = `-- name: CountMaintenanceAll :one
SELECT COUNT(*) FROM maintenance_windows
`

func (q *Queries) CountMaintenanceAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaintenanceAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countMaintenanceFiltered = `-- name: CountMaintenanceFiltered :one
SELECT COUNT(*) FROM maintenance_windows WHERE state = ?
`

func (q *Queries) CountMaintenanceFiltered(ctx context.Context, state string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMaintenanceFiltered, state)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMaintenanceWindow = `-- name: CreateMaintenanceWindow :one
INSERT INTO maintenance_windows (
    title, description, starts_at, ends_at, state, created_by_user_id
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at
`

type CreateMaintenanceWindowParams struct {
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	StartsAt        time.Time      `json:"starts_at"`
	EndsAt          time.Time      `json:"ends_at"`
	State           string         `json:"state"`
	CreatedByUserID sql.NullInt64  `json:"created_by_user_id"`
}

func (q *Queries) CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error) {
	row := q.db.QueryRowContext(ctx, createMaintenanceWindow,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.State,
		arg.CreatedByUserID,
	)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.State,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMaintenanceWindow = `-- name: DeleteMaintenanceWindow :exec
DELETE FROM maintenance_windows WHERE id = ?
`

func (q *Queries) DeleteMaintenanceWindow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMaintenanceWindow, id)
	return err
}

const endMaintenanceNow = `-- name: EndMaintenanceNow :execrows
UPDATE maintenance_windows
SET state = 'completed', ends_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ? AND state = 'in_progress'
`

func (q *Queries) EndMaintenanceNow(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, endMaintenanceNow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getMaintenanceWindow = `-- name: GetMaintenanceWindow :one
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows WHERE id = ? LIMIT 1
`

func (q *Queries) GetMaintenanceWindow(ctx context.Context, id int64) (MaintenanceWindow, error) {
	row := q.db.QueryRowContext(ctx, getMaintenanceWindow, id)
	var i MaintenanceWindow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.State,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMaintenance = `-- name: ListActiveMaintenance :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows WHERE state = 'in_progress' ORDER BY starts_at ASC
`

func (q *Queries) ListActiveMaintenance(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMaintenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceAll = `-- name: ListMaintenanceAll :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows
ORDER BY starts_at DESC
LIMIT ? OFFSET ?
`

type ListMaintenanceAllParams struct {
	Limit  int64 `json:"limit"`
	Offset int64 `json:"offset"`
}

func (q *Queries) ListMaintenanceAll(ctx context.Context, arg ListMaintenanceAllParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceAll, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceBetween = `-- name: ListMaintenanceBetween :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows
WHERE starts_at < ? AND ends_at > ?
ORDER BY starts_at ASC
`

type ListMaintenanceBetweenParams struct {
	StartsAt time.Time `json:"starts_at"`
	EndsAt   time.Time `json:"ends_at"`
}

func (q *Queries) ListMaintenanceBetween(ctx context.Context, arg ListMaintenanceBetweenParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceBetween, arg.StartsAt, arg.EndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceFiltered = `-- name: ListMaintenanceFiltered :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows
WHERE state = ?
ORDER BY starts_at DESC
LIMIT ? OFFSET ?
`

type ListMaintenanceFilteredParams struct {
	State  string `json:"state"`
	Limit  int64  `json:"limit"`
	Offset int64  `json:"offset"`
}

func (q *Queries) ListMaintenanceFiltered(ctx context.Context, arg ListMaintenanceFilteredParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceFiltered, arg.State, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceWindows = `-- name: ListMaintenanceWindows :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows ORDER BY starts_at DESC LIMIT ?
`

func (q *Queries) ListMaintenanceWindows(ctx context.Context, limit int64) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceWindows, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPastMaintenance = `-- name: ListPastMaintenance :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows
WHERE state IN ('completed','cancelled') AND ends_at > ?
ORDER BY ends_at DESC
LIMIT ?
`

type ListPastMaintenanceParams struct {
	EndsAt time.Time `json:"ends_at"`
	Limit  int64     `json:"limit"`
}

func (q *Queries) ListPastMaintenance(ctx context.Context, arg ListPastMaintenanceParams) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listPastMaintenance, arg.EndsAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMaintenance = `-- name: ListUpcomingMaintenance :many
SELECT id, title, description, starts_at, ends_at, state, created_by_user_id, created_at, updated_at FROM maintenance_windows
WHERE state = 'scheduled' AND starts_at > datetime('now')
ORDER BY starts_at ASC
`

func (q *Queries) ListUpcomingMaintenance(ctx context.Context) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingMaintenance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenanceState = `-- name: UpdateMaintenanceState :exec
UPDATE maintenance_windows
SET state      = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMaintenanceStateParams struct {
	State string `json:"state"`
	ID    int64  `json:"id"`
}

func (q *Queries) UpdateMaintenanceState(ctx context.Context, arg UpdateMaintenanceStateParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceState, arg.State, arg.ID)
	return err
}

const updateMaintenanceWindow = `-- name: UpdateMaintenanceWindow :exec
UPDATE maintenance_windows
SET title       = ?,
    description = ?,
    starts_at   = ?,
    ends_at     = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateMaintenanceWindowParams struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	StartsAt    time.Time      `json:"starts_at"`
	EndsAt      time.Time      `json:"ends_at"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) error {
	_, err := q.db.ExecContext(ctx, updateMaintenanceWindow,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.ID,
	)
	return err
}
