// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: maintenance_affected_components.sql

package store

import (
	"context"
)

const linkComponent = `-- name: LinkComponent :exec
INSERT OR IGNORE INTO maintenance_affected_components (maintenance_id, component_id)
VALUES (?, ?)
`

type LinkComponentParams struct {
	MaintenanceID int64 `json:"maintenance_id"`
	ComponentID   int64 `json:"component_id"`
}

func (q *Queries) LinkComponent(ctx context.Context, arg LinkComponentParams) error {
	_, err := q.db.ExecContext(ctx, linkComponent, arg.MaintenanceID, arg.ComponentID)
	return err
}

const listAffectedComponents = `-- name: ListAffectedComponents :many
SELECT components.id, components.name, components.description, components.display_order, components.created_at, components.updated_at
FROM maintenance_affected_components
JOIN components ON components.id = maintenance_affected_components.component_id
WHERE maintenance_affected_components.maintenance_id = ?
ORDER BY components.display_order ASC, components.name ASC
`

func (q *Queries) ListAffectedComponents(ctx context.Context, maintenanceID int64) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listAffectedComponents, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listComponentsForMaintenance = `-- name: ListComponentsForMaintenance :many
SELECT component_id FROM maintenance_affected_components
WHERE maintenance_id = ?
`

func (q *Queries) ListComponentsForMaintenance(ctx context.Context, maintenanceID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listComponentsForMaintenance, maintenanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var component_id int64
		if err := rows.Scan(&component_id); err != nil {
			return nil, err
		}
		items = append(items, component_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceForComponent = `-- name: ListMaintenanceForComponent :many
SELECT maintenance_windows.id, maintenance_windows.title, maintenance_windows.description, maintenance_windows.starts_at, maintenance_windows.ends_at, maintenance_windows.state, maintenance_windows.created_by_user_id, maintenance_windows.created_at, maintenance_windows.updated_at
FROM maintenance_affected_components
JOIN maintenance_windows ON maintenance_windows.id = maintenance_affected_components.maintenance_id
WHERE maintenance_affected_components.component_id = ?
  AND maintenance_windows.state = 'in_progress'
ORDER BY maintenance_windows.starts_at ASC
`

func (q *Queries) ListMaintenanceForComponent(ctx context.Context, componentID int64) ([]MaintenanceWindow, error) {
	rows, err := q.db.QueryContext(ctx, listMaintenanceForComponent, componentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceWindow{}
	for rows.Next() {
		var i MaintenanceWindow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.State,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkComponent = `-- name: UnlinkComponent :exec
DELETE FROM maintenance_affected_components
WHERE maintenance_id = ? AND component_id = ?
`

type UnlinkComponentParams struct {
	MaintenanceID int64 `json:"maintenance_id"`
	ComponentID   int64 `json:"component_id"`
}

func (q *Queries) UnlinkComponent(ctx context.Context, arg UnlinkComponentParams) error {
	_, err := q.db.ExecContext(ctx, unlinkComponent, arg.MaintenanceID, arg.ComponentID)
	return err
}
