// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"
)

type Check struct {
	ID                   int64          `json:"id"`
	Name                 string         `json:"name"`
	Type                 string         `json:"type"`
	Enabled              bool           `json:"enabled"`
	IntervalSeconds      int64          `json:"interval_seconds"`
	TimeoutSeconds       int64          `json:"timeout_seconds"`
	Retries              int64          `json:"retries"`
	FailureThreshold     int64          `json:"failure_threshold"`
	RecoveryThreshold    int64          `json:"recovery_threshold"`
	ConfigJson           string         `json:"config_json"`
	ComponentID          sql.NullInt64  `json:"component_id"`
	LastStatus           string         `json:"last_status"`
	LastLatencyMs        sql.NullInt64  `json:"last_latency_ms"`
	LastCheckedAt        sql.NullTime   `json:"last_checked_at"`
	ConsecutiveFailures  int64          `json:"consecutive_failures"`
	ConsecutiveSuccesses int64          `json:"consecutive_successes"`
	CreatedAt            time.Time      `json:"created_at"`
	UpdatedAt            time.Time      `json:"updated_at"`
	PushToken            sql.NullString `json:"push_token"`
	ReopenWindowSeconds  sql.NullInt64  `json:"reopen_window_seconds"`
	ReopenMode           sql.NullString `json:"reopen_mode"`
}

type CheckNotificationChannel struct {
	CheckID   int64 `json:"check_id"`
	ChannelID int64 `json:"channel_id"`
}

type CheckResult struct {
	ID                   int64          `json:"id"`
	CheckID              int64          `json:"check_id"`
	CheckedAt            time.Time      `json:"checked_at"`
	Status               string         `json:"status"`
	LatencyMs            sql.NullInt64  `json:"latency_ms"`
	ErrorMessage         sql.NullString `json:"error_message"`
	ResponseMetadataJson sql.NullString `json:"response_metadata_json"`
}

type CheckResultsDaily struct {
	ID            int64           `json:"id"`
	CheckID       int64           `json:"check_id"`
	DayBucket     time.Time       `json:"day_bucket"`
	TotalCount    int64           `json:"total_count"`
	UpCount       int64           `json:"up_count"`
	DegradedCount int64           `json:"degraded_count"`
	DownCount     int64           `json:"down_count"`
	UnknownCount  int64           `json:"unknown_count"`
	AvgLatencyMs  sql.NullFloat64 `json:"avg_latency_ms"`
	MinLatencyMs  sql.NullInt64   `json:"min_latency_ms"`
	MaxLatencyMs  sql.NullInt64   `json:"max_latency_ms"`
	P95LatencyMs  sql.NullInt64   `json:"p95_latency_ms"`
}

type CheckResultsHourly struct {
	ID            int64           `json:"id"`
	CheckID       int64           `json:"check_id"`
	HourBucket    time.Time       `json:"hour_bucket"`
	TotalCount    int64           `json:"total_count"`
	UpCount       int64           `json:"up_count"`
	DegradedCount int64           `json:"degraded_count"`
	DownCount     int64           `json:"down_count"`
	UnknownCount  int64           `json:"unknown_count"`
	AvgLatencyMs  sql.NullFloat64 `json:"avg_latency_ms"`
	MinLatencyMs  sql.NullInt64   `json:"min_latency_ms"`
	MaxLatencyMs  sql.NullInt64   `json:"max_latency_ms"`
	P95LatencyMs  sql.NullInt64   `json:"p95_latency_ms"`
}

type Component struct {
	ID           int64          `json:"id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	DisplayOrder int64          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

type Incident struct {
	ID                int64         `json:"id"`
	Title             string        `json:"title"`
	Status            string        `json:"status"`
	Severity          string        `json:"severity"`
	StartedAt         time.Time     `json:"started_at"`
	ResolvedAt        sql.NullTime  `json:"resolved_at"`
	AutoCreated       bool          `json:"auto_created"`
	TriggeringCheckID sql.NullInt64 `json:"triggering_check_id"`
	CreatedByUserID   sql.NullInt64 `json:"created_by_user_id"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
}

type IncidentAffectedCheck struct {
	IncidentID int64 `json:"incident_id"`
	CheckID    int64 `json:"check_id"`
}

type IncidentUpdate struct {
	ID             int64         `json:"id"`
	IncidentID     int64         `json:"incident_id"`
	Status         string        `json:"status"`
	Message        string        `json:"message"`
	PostedByUserID sql.NullInt64 `json:"posted_by_user_id"`
	AutoGenerated  bool          `json:"auto_generated"`
	CreatedAt      time.Time     `json:"created_at"`
}

type MaintenanceAffectedComponent struct {
	MaintenanceID int64 `json:"maintenance_id"`
	ComponentID   int64 `json:"component_id"`
}

type MaintenanceWindow struct {
	ID              int64          `json:"id"`
	Title           string         `json:"title"`
	Description     sql.NullString `json:"description"`
	StartsAt        time.Time      `json:"starts_at"`
	EndsAt          time.Time      `json:"ends_at"`
	State           string         `json:"state"`
	CreatedByUserID sql.NullInt64  `json:"created_by_user_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type NotificationChannel struct {
	ID                  int64     `json:"id"`
	Name                string    `json:"name"`
	Type                string    `json:"type"`
	Enabled             bool      `json:"enabled"`
	ConfigJson          string    `json:"config_json"`
	RetryMax            int64     `json:"retry_max"`
	RetryBackoffSeconds int64     `json:"retry_backoff_seconds"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type NotificationDelivery struct {
	ID              int64          `json:"id"`
	ChannelID       int64          `json:"channel_id"`
	EventType       string         `json:"event_type"`
	EventID         int64          `json:"event_id"`
	PayloadJson     string         `json:"payload_json"`
	Status          string         `json:"status"`
	AttemptCount    int64          `json:"attempt_count"`
	LastAttemptedAt sql.NullTime   `json:"last_attempted_at"`
	LastError       sql.NullString `json:"last_error"`
	NextAttemptAt   sql.NullTime   `json:"next_attempt_at"`
	CreatedAt       time.Time      `json:"created_at"`
	SentAt          sql.NullTime   `json:"sent_at"`
}

type RecoveryCode struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	CodeHash  string       `json:"code_hash"`
	UsedAt    sql.NullTime `json:"used_at"`
	CreatedAt time.Time    `json:"created_at"`
}

type RetentionSetting struct {
	ID               int64     `json:"id"`
	RawDays          int64     `json:"raw_days"`
	HourlyDays       int64     `json:"hourly_days"`
	DailyDays        int64     `json:"daily_days"`
	KeepDailyForever bool      `json:"keep_daily_forever"`
	UpdatedAt        time.Time `json:"updated_at"`
}

type Session struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

type StatusPage struct {
	ID               int64          `json:"id"`
	Slug             string         `json:"slug"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	LogoUrl          sql.NullString `json:"logo_url"`
	AccentColor      sql.NullString `json:"accent_color"`
	CustomFooterHtml sql.NullString `json:"custom_footer_html"`
	PasswordHash     sql.NullString `json:"password_hash"`
	IsDefault        bool           `json:"is_default"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	FooterMode       string         `json:"footer_mode"`
	HidePoweredBy    bool           `json:"hide_powered_by"`
	ShowHistory      bool           `json:"show_history"`
}

type StatusPageComponent struct {
	StatusPageID        int64  `json:"status_page_id"`
	ComponentID         int64  `json:"component_id"`
	DisplayOrder        int64  `json:"display_order"`
	ShowMonitorsDefault string `json:"show_monitors_default"`
}

type StatusPageDomain struct {
	ID           int64     `json:"id"`
	StatusPageID int64     `json:"status_page_id"`
	Domain       string    `json:"domain"`
	CreatedAt    time.Time `json:"created_at"`
}

type StatusPageFooterElement struct {
	ID           int64          `json:"id"`
	StatusPageID int64          `json:"status_page_id"`
	ElementType  string         `json:"element_type"`
	Label        sql.NullString `json:"label"`
	Url          sql.NullString `json:"url"`
	OpenInNewTab bool           `json:"open_in_new_tab"`
	DisplayOrder int64          `json:"display_order"`
	CreatedAt    time.Time      `json:"created_at"`
}

type StatusPageMonitor struct {
	StatusPageID int64 `json:"status_page_id"`
	CheckID      int64 `json:"check_id"`
	DisplayOrder int64 `json:"display_order"`
}

type SystemSetting struct {
	ID                          int64     `json:"id"`
	IncidentIDFormat            string    `json:"incident_id_format"`
	IncidentReopenWindowSeconds int64     `json:"incident_reopen_window_seconds"`
	IncidentReopenMode          string    `json:"incident_reopen_mode"`
	UpdatedAt                   time.Time `json:"updated_at"`
}

type User struct {
	ID             int64          `json:"id"`
	Username       string         `json:"username"`
	Email          string         `json:"email"`
	DisplayName    string         `json:"display_name"`
	PasswordHash   string         `json:"password_hash"`
	Role           string         `json:"role"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
	TotpSecretEnc  sql.NullString `json:"totp_secret_enc"`
	TotpEnabled    bool           `json:"totp_enabled"`
	TotpEnrolledAt sql.NullTime   `json:"totp_enrolled_at"`
}
