// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_deliveries.sql

package store

import (
	"context"
	"database/sql"
)

const countDeliveriesForEvent = `-- name: CountDeliveriesForEvent :one
SELECT COUNT(*) FROM notification_deliveries
WHERE channel_id = ? AND event_type = ? AND event_id = ?
`

type CountDeliveriesForEventParams struct {
	ChannelID int64  `json:"channel_id"`
	EventType string `json:"event_type"`
	EventID   int64  `json:"event_id"`
}

func (q *Queries) CountDeliveriesForEvent(ctx context.Context, arg CountDeliveriesForEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeliveriesForEvent, arg.ChannelID, arg.EventType, arg.EventID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationDelivery = `-- name: CreateNotificationDelivery :one
INSERT INTO notification_deliveries (
    channel_id, event_type, event_id, payload_json, status, next_attempt_at
) VALUES (
    ?, ?, ?, ?, 'pending', ?
)
RETURNING id, channel_id, event_type, event_id, payload_json, status, attempt_count, last_attempted_at, last_error, next_attempt_at, created_at, sent_at
`

type CreateNotificationDeliveryParams struct {
	ChannelID     int64        `json:"channel_id"`
	EventType     string       `json:"event_type"`
	EventID       int64        `json:"event_id"`
	PayloadJson   string       `json:"payload_json"`
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
}

func (q *Queries) CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, createNotificationDelivery,
		arg.ChannelID,
		arg.EventType,
		arg.EventID,
		arg.PayloadJson,
		arg.NextAttemptAt,
	)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.PayloadJson,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptedAt,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const getNotificationDelivery = `-- name: GetNotificationDelivery :one
SELECT id, channel_id, event_type, event_id, payload_json, status, attempt_count, last_attempted_at, last_error, next_attempt_at, created_at, sent_at FROM notification_deliveries WHERE id = ? LIMIT 1
`

func (q *Queries) GetNotificationDelivery(ctx context.Context, id int64) (NotificationDelivery, error) {
	row := q.db.QueryRowContext(ctx, getNotificationDelivery, id)
	var i NotificationDelivery
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.EventType,
		&i.EventID,
		&i.PayloadJson,
		&i.Status,
		&i.AttemptCount,
		&i.LastAttemptedAt,
		&i.LastError,
		&i.NextAttemptAt,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT id, channel_id, event_type, event_id, payload_json, status, attempt_count, last_attempted_at, last_error, next_attempt_at, created_at, sent_at FROM notification_deliveries
WHERE status = 'pending' AND (next_attempt_at IS NULL OR next_attempt_at <= ?)
ORDER BY id ASC
LIMIT ?
`

type ListPendingDeliveriesParams struct {
	NextAttemptAt sql.NullTime `json:"next_attempt_at"`
	Limit         int64        `json:"limit"`
}

func (q *Queries) ListPendingDeliveries(ctx context.Context, arg ListPendingDeliveriesParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listPendingDeliveries, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.EventType,
			&i.EventID,
			&i.PayloadJson,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptedAt,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDeliveriesForChannel = `-- name: ListRecentDeliveriesForChannel :many
SELECT id, channel_id, event_type, event_id, payload_json, status, attempt_count, last_attempted_at, last_error, next_attempt_at, created_at, sent_at FROM notification_deliveries
WHERE channel_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListRecentDeliveriesForChannelParams struct {
	ChannelID int64 `json:"channel_id"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) ListRecentDeliveriesForChannel(ctx context.Context, arg ListRecentDeliveriesForChannelParams) ([]NotificationDelivery, error) {
	rows, err := q.db.QueryContext(ctx, listRecentDeliveriesForChannel, arg.ChannelID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationDelivery{}
	for rows.Next() {
		var i NotificationDelivery
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.EventType,
			&i.EventID,
			&i.PayloadJson,
			&i.Status,
			&i.AttemptCount,
			&i.LastAttemptedAt,
			&i.LastError,
			&i.NextAttemptAt,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE notification_deliveries
SET status        = 'failed',
    attempt_count = attempt_count + 1,
    last_error    = ?
WHERE id = ?
`

type MarkDeliveryFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryFailed, arg.LastError, arg.ID)
	return err
}

const markDeliveryRetry = `-- name: MarkDeliveryRetry :exec
UPDATE notification_deliveries
SET status          = 'pending',
    attempt_count   = attempt_count + 1,
    last_error      = ?,
    next_attempt_at = ?
WHERE id = ?
`

type MarkDeliveryRetryParams struct {
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt sql.NullTime   `json:"next_attempt_at"`
	ID            int64          `json:"id"`
}

func (q *Queries) MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error {
	_, err := q.db.ExecContext(ctx, markDeliveryRetry, arg.LastError, arg.NextAttemptAt, arg.ID)
	return err
}

const markDeliverySending = `-- name: MarkDeliverySending :exec
UPDATE notification_deliveries
SET status            = 'sending',
    last_attempted_at = ?
WHERE id = ?
`

type MarkDeliverySendingParams struct {
	LastAttemptedAt sql.NullTime `json:"last_attempted_at"`
	ID              int64        `json:"id"`
}

func (q *Queries) MarkDeliverySending(ctx context.Context, arg MarkDeliverySendingParams) error {
	_, err := q.db.ExecContext(ctx, markDeliverySending, arg.LastAttemptedAt, arg.ID)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE notification_deliveries
SET status        = 'sent',
    attempt_count = attempt_count + 1,
    sent_at       = ?,
    last_error    = NULL
WHERE id = ?
`

type MarkDeliverySentParams struct {
	SentAt sql.NullTime `json:"sent_at"`
	ID     int64        `json:"id"`
}

func (q *Queries) MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error {
	_, err := q.db.ExecContext(ctx, markDeliverySent, arg.SentAt, arg.ID)
	return err
}
