// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification_channels.sql

package store

import (
	"context"
)

const countChecksForChannel = `-- name: CountChecksForChannel :one
SELECT COUNT(*) FROM check_notification_channels WHERE channel_id = ?
`

func (q *Queries) CountChecksForChannel(ctx context.Context, channelID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChecksForChannel, channelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channels (
    name, type, enabled, config_json, retry_max, retry_backoff_seconds
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, name, type, enabled, config_json, retry_max, retry_backoff_seconds, created_at, updated_at
`

type CreateNotificationChannelParams struct {
	Name                string `json:"name"`
	Type                string `json:"type"`
	Enabled             bool   `json:"enabled"`
	ConfigJson          string `json:"config_json"`
	RetryMax            int64  `json:"retry_max"`
	RetryBackoffSeconds int64  `json:"retry_backoff_seconds"`
}

func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, createNotificationChannel,
		arg.Name,
		arg.Type,
		arg.Enabled,
		arg.ConfigJson,
		arg.RetryMax,
		arg.RetryBackoffSeconds,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ConfigJson,
		&i.RetryMax,
		&i.RetryBackoffSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels WHERE id = ?
`

func (q *Queries) DeleteNotificationChannel(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationChannel, id)
	return err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, name, type, enabled, config_json, retry_max, retry_backoff_seconds, created_at, updated_at FROM notification_channels WHERE id = ? LIMIT 1
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id int64) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ConfigJson,
		&i.RetryMax,
		&i.RetryBackoffSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledNotificationChannels = `-- name: ListEnabledNotificationChannels :many
SELECT id, name, type, enabled, config_json, retry_max, retry_backoff_seconds, created_at, updated_at FROM notification_channels WHERE enabled = 1 ORDER BY name ASC
`

func (q *Queries) ListEnabledNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listEnabledNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.ConfigJson,
			&i.RetryMax,
			&i.RetryBackoffSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, name, type, enabled, config_json, retry_max, retry_backoff_seconds, created_at, updated_at FROM notification_channels ORDER BY name ASC
`

func (q *Queries) ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.ConfigJson,
			&i.RetryMax,
			&i.RetryBackoffSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET name                  = ?,
    enabled               = ?,
    config_json           = ?,
    retry_max             = ?,
    retry_backoff_seconds = ?,
    updated_at            = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, enabled, config_json, retry_max, retry_backoff_seconds, created_at, updated_at
`

type UpdateNotificationChannelParams struct {
	Name                string `json:"name"`
	Enabled             bool   `json:"enabled"`
	ConfigJson          string `json:"config_json"`
	RetryMax            int64  `json:"retry_max"`
	RetryBackoffSeconds int64  `json:"retry_backoff_seconds"`
	ID                  int64  `json:"id"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationChannel,
		arg.Name,
		arg.Enabled,
		arg.ConfigJson,
		arg.RetryMax,
		arg.RetryBackoffSeconds,
		arg.ID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Enabled,
		&i.ConfigJson,
		&i.RetryMax,
		&i.RetryBackoffSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
