// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddComponentToStatusPage(ctx context.Context, arg AddComponentToStatusPageParams) error
	AutoCompleteDueMaintenance(ctx context.Context) error
	AutoStartDueMaintenance(ctx context.Context) error
	CancelMaintenance(ctx context.Context, id int64) (int64, error)
	ClearChannelsForCheck(ctx context.Context, checkID int64) error
	CountChecksByStatus(ctx context.Context) ([]CountChecksByStatusRow, error)
	CountChecksForChannel(ctx context.Context, channelID int64) (int64, error)
	CountChecksForComponent(ctx context.Context, componentID sql.NullInt64) (int64, error)
	CountDeliveriesForEvent(ctx context.Context, arg CountDeliveriesForEventParams) (int64, error)
	CountMaintenanceAll(ctx context.Context) (int64, error)
	CountMaintenanceFiltered(ctx context.Context, state string) (int64, error)
	CountResultsByStatusInRange(ctx context.Context, arg CountResultsByStatusInRangeParams) ([]CountResultsByStatusInRangeRow, error)
	CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersByRole(ctx context.Context, role string) (int64, error)
	CreateCheck(ctx context.Context, arg CreateCheckParams) (Check, error)
	CreateComponent(ctx context.Context, arg CreateComponentParams) (Component, error)
	CreateFooterElement(ctx context.Context, arg CreateFooterElementParams) (StatusPageFooterElement, error)
	CreateIncident(ctx context.Context, arg CreateIncidentParams) (Incident, error)
	CreateIncidentUpdate(ctx context.Context, arg CreateIncidentUpdateParams) (IncidentUpdate, error)
	CreateMaintenanceWindow(ctx context.Context, arg CreateMaintenanceWindowParams) (MaintenanceWindow, error)
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error)
	CreateNotificationDelivery(ctx context.Context, arg CreateNotificationDeliveryParams) (NotificationDelivery, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (RecoveryCode, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCheck(ctx context.Context, id int64) error
	DeleteComponent(ctx context.Context, id int64) error
	DeleteDailyOlderThan(ctx context.Context, dayBucket time.Time) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteFooterElement(ctx context.Context, id int64) error
	DeleteFooterElementsForPage(ctx context.Context, statusPageID int64) error
	DeleteHourlyOlderThan(ctx context.Context, hourBucket time.Time) error
	DeleteIncident(ctx context.Context, id int64) error
	DeleteMaintenanceWindow(ctx context.Context, id int64) error
	DeleteNotificationChannel(ctx context.Context, id int64) error
	DeleteRecoveryCodesForUser(ctx context.Context, userID int64) error
	DeleteResultsOlderThan(ctx context.Context, checkedAt time.Time) error
	DeleteSession(ctx context.Context, id string) error
	DeleteSessionsForUser(ctx context.Context, userID int64) error
	DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) error
	DeleteStatusPage(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DisableUserTOTP(ctx context.Context, id int64) error
	EnableUserTOTP(ctx context.Context, id int64) error
	EndMaintenanceNow(ctx context.Context, id int64) (int64, error)
	ExtendSession(ctx context.Context, arg ExtendSessionParams) error
	GetCheck(ctx context.Context, id int64) (Check, error)
	GetCheckByPushToken(ctx context.Context, pushToken sql.NullString) (Check, error)
	GetComponent(ctx context.Context, id int64) (Component, error)
	GetDailyInRange(ctx context.Context, arg GetDailyInRangeParams) ([]CheckResultsDaily, error)
	GetDefaultStatusPage(ctx context.Context) (StatusPage, error)
	GetHourlyForRollup(ctx context.Context, arg GetHourlyForRollupParams) ([]CheckResultsHourly, error)
	GetHourlyInRange(ctx context.Context, arg GetHourlyInRangeParams) ([]CheckResultsHourly, error)
	GetIncident(ctx context.Context, id int64) (Incident, error)
	GetMaintenanceWindow(ctx context.Context, id int64) (MaintenanceWindow, error)
	GetMostRecentResolvedIncidentForCheck(ctx context.Context, checkID int64) (Incident, error)
	GetMostRecentResult(ctx context.Context, checkID int64) (CheckResult, error)
	GetNotificationChannel(ctx context.Context, id int64) (NotificationChannel, error)
	GetNotificationDelivery(ctx context.Context, id int64) (NotificationDelivery, error)
	GetOldestHourly(ctx context.Context, checkID int64) (interface{}, error)
	GetOldestRawResult(ctx context.Context, checkID int64) (interface{}, error)
	GetRawResultsForRollup(ctx context.Context, arg GetRawResultsForRollupParams) ([]CheckResult, error)
	GetRecentResults(ctx context.Context, arg GetRecentResultsParams) ([]CheckResult, error)
	GetResultsInRange(ctx context.Context, arg GetResultsInRangeParams) ([]CheckResult, error)
	GetRetentionSettings(ctx context.Context) (RetentionSetting, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error)
	GetStatusPage(ctx context.Context, id int64) (StatusPage, error)
	GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error)
	GetSystemSettings(ctx context.Context) (SystemSetting, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertCheckResult(ctx context.Context, arg InsertCheckResultParams) error
	LinkCheckToChannel(ctx context.Context, arg LinkCheckToChannelParams) error
	LinkCheckToIncident(ctx context.Context, arg LinkCheckToIncidentParams) error
	LinkComponent(ctx context.Context, arg LinkComponentParams) error
	ListActiveIncidents(ctx context.Context) ([]Incident, error)
	ListActiveMaintenance(ctx context.Context) ([]MaintenanceWindow, error)
	ListAffectedCheckIDsForIncident(ctx context.Context, incidentID int64) ([]int64, error)
	ListAffectedComponents(ctx context.Context, maintenanceID int64) ([]Component, error)
	ListChannelRowsForCheck(ctx context.Context, checkID int64) ([]NotificationChannel, error)
	ListChannelsForCheck(ctx context.Context, checkID int64) ([]int64, error)
	ListChecks(ctx context.Context) ([]Check, error)
	ListChecksForChannel(ctx context.Context, channelID int64) ([]int64, error)
	ListChecksForComponent(ctx context.Context, componentID sql.NullInt64) ([]Check, error)
	ListChecksForIncident(ctx context.Context, incidentID int64) ([]Check, error)
	ListChecksWithHourly(ctx context.Context) ([]int64, error)
	ListChecksWithRawResults(ctx context.Context) ([]int64, error)
	ListComponents(ctx context.Context) ([]Component, error)
	ListComponentsForMaintenance(ctx context.Context, maintenanceID int64) ([]int64, error)
	ListComponentsForStatusPage(ctx context.Context, statusPageID int64) ([]Component, error)
	ListEnabledChecksDue(ctx context.Context) ([]Check, error)
	ListEnabledNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	ListEnabledPushChecks(ctx context.Context) ([]Check, error)
	ListFooterElements(ctx context.Context, statusPageID int64) ([]StatusPageFooterElement, error)
	ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]Incident, error)
	ListIncidentsForCheck(ctx context.Context, arg ListIncidentsForCheckParams) ([]Incident, error)
	ListMaintenanceAll(ctx context.Context, arg ListMaintenanceAllParams) ([]MaintenanceWindow, error)
	ListMaintenanceBetween(ctx context.Context, arg ListMaintenanceBetweenParams) ([]MaintenanceWindow, error)
	ListMaintenanceFiltered(ctx context.Context, arg ListMaintenanceFilteredParams) ([]MaintenanceWindow, error)
	ListMaintenanceForComponent(ctx context.Context, componentID int64) ([]MaintenanceWindow, error)
	ListMaintenanceWindows(ctx context.Context, limit int64) ([]MaintenanceWindow, error)
	ListNotificationChannels(ctx context.Context) ([]NotificationChannel, error)
	ListPastMaintenance(ctx context.Context, arg ListPastMaintenanceParams) ([]MaintenanceWindow, error)
	ListPendingDeliveries(ctx context.Context, arg ListPendingDeliveriesParams) ([]NotificationDelivery, error)
	ListRecentDeliveriesForChannel(ctx context.Context, arg ListRecentDeliveriesForChannelParams) ([]NotificationDelivery, error)
	ListRecentResolvedIncidents(ctx context.Context, limit int64) ([]Incident, error)
	ListSessionsForUser(ctx context.Context, userID int64) ([]Session, error)
	ListStatusPages(ctx context.Context) ([]StatusPage, error)
	ListUnusedRecoveryCodesForUser(ctx context.Context, userID int64) ([]RecoveryCode, error)
	ListUpcomingMaintenance(ctx context.Context) ([]MaintenanceWindow, error)
	ListUpdatesForIncident(ctx context.Context, incidentID int64) ([]IncidentUpdate, error)
	ListUsers(ctx context.Context) ([]User, error)
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error
	MarkDeliveryRetry(ctx context.Context, arg MarkDeliveryRetryParams) error
	MarkDeliverySending(ctx context.Context, arg MarkDeliverySendingParams) error
	MarkDeliverySent(ctx context.Context, arg MarkDeliverySentParams) error
	MarkRecoveryCodeUsed(ctx context.Context, id int64) error
	RemoveAllComponentsFromStatusPage(ctx context.Context, statusPageID int64) error
	RemoveComponentFromStatusPage(ctx context.Context, arg RemoveComponentFromStatusPageParams) error
	SetCheckPushToken(ctx context.Context, arg SetCheckPushTokenParams) error
	SetStatusPageAsDefault(ctx context.Context, id int64) error
	SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error
	UnlinkCheckFromChannel(ctx context.Context, arg UnlinkCheckFromChannelParams) error
	UnlinkCheckFromIncident(ctx context.Context, arg UnlinkCheckFromIncidentParams) error
	UnlinkComponent(ctx context.Context, arg UnlinkComponentParams) error
	UnsetAllDefaults(ctx context.Context) error
	UpdateCheck(ctx context.Context, arg UpdateCheckParams) (Check, error)
	UpdateCheckStatus(ctx context.Context, arg UpdateCheckStatusParams) error
	UpdateComponent(ctx context.Context, arg UpdateComponentParams) error
	UpdateFooterElement(ctx context.Context, arg UpdateFooterElementParams) error
	UpdateIncidentMetadata(ctx context.Context, arg UpdateIncidentMetadataParams) error
	UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) error
	UpdateMaintenanceState(ctx context.Context, arg UpdateMaintenanceStateParams) error
	UpdateMaintenanceWindow(ctx context.Context, arg UpdateMaintenanceWindowParams) error
	UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error)
	UpdateRetentionSettings(ctx context.Context, arg UpdateRetentionSettingsParams) error
	UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) error
	UpdateStatusPageComponentOrder(ctx context.Context, arg UpdateStatusPageComponentOrderParams) error
	UpdateStatusPageFooterMode(ctx context.Context, arg UpdateStatusPageFooterModeParams) error
	UpdateStatusPagePassword(ctx context.Context, arg UpdateStatusPagePasswordParams) error
	UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) error
	UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertCheckResultDaily(ctx context.Context, arg UpsertCheckResultDailyParams) error
	UpsertCheckResultHourly(ctx context.Context, arg UpsertCheckResultHourlyParams) error
}

var _ Querier = (*Queries)(nil)
