// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recovery_codes.sql

package store

import (
	"context"
)

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT COUNT(*) FROM recovery_codes
WHERE user_id = ? AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :one
INSERT INTO recovery_codes (user_id, code_hash)
VALUES (?, ?)
RETURNING id, user_id, code_hash, used_at, created_at
`

type CreateRecoveryCodeParams struct {
	UserID   int64  `json:"user_id"`
	CodeHash string `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) (RecoveryCode, error) {
	row := q.db.QueryRowContext(ctx, createRecoveryCode, arg.UserID, arg.CodeHash)
	var i RecoveryCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :exec
DELETE FROM recovery_codes WHERE user_id = ?
`

func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteRecoveryCodesForUser, userID)
	return err
}

const listUnusedRecoveryCodesForUser = `-- name: ListUnusedRecoveryCodesForUser :many
SELECT id, user_id, code_hash, used_at, created_at FROM recovery_codes
WHERE user_id = ? AND used_at IS NULL
ORDER BY id ASC
`

func (q *Queries) ListUnusedRecoveryCodesForUser(ctx context.Context, userID int64) ([]RecoveryCode, error) {
	rows, err := q.db.QueryContext(ctx, listUnusedRecoveryCodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecoveryCode{}
	for rows.Next() {
		var i RecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRecoveryCodeUsed = `-- name: MarkRecoveryCodeUsed :exec
UPDATE recovery_codes SET used_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) MarkRecoveryCodeUsed(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markRecoveryCodeUsed, id)
	return err
}
