// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retention.sql

package store

import (
	"context"
)

const getRetentionSettings = `-- name: GetRetentionSettings :one
SELECT id, raw_days, hourly_days, daily_days, keep_daily_forever, updated_at FROM retention_settings WHERE id = 1 LIMIT 1
`

func (q *Queries) GetRetentionSettings(ctx context.Context) (RetentionSetting, error) {
	row := q.db.QueryRowContext(ctx, getRetentionSettings)
	var i RetentionSetting
	err := row.Scan(
		&i.ID,
		&i.RawDays,
		&i.HourlyDays,
		&i.DailyDays,
		&i.KeepDailyForever,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRetentionSettings = `-- name: UpdateRetentionSettings :exec
UPDATE retention_settings
SET raw_days           = ?,
    hourly_days        = ?,
    daily_days         = ?,
    keep_daily_forever = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateRetentionSettingsParams struct {
	RawDays          int64 `json:"raw_days"`
	HourlyDays       int64 `json:"hourly_days"`
	DailyDays        int64 `json:"daily_days"`
	KeepDailyForever bool  `json:"keep_daily_forever"`
}

func (q *Queries) UpdateRetentionSettings(ctx context.Context, arg UpdateRetentionSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateRetentionSettings,
		arg.RawDays,
		arg.HourlyDays,
		arg.DailyDays,
		arg.KeepDailyForever,
	)
	return err
}
