// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, expires_at, user_agent, ip_address)
VALUES (?, ?, ?, ?, ?)
RETURNING id, user_id, expires_at, created_at, user_agent, ip_address
`

type CreateSessionParams struct {
	ID        string         `json:"id"`
	UserID    int64          `json:"user_id"`
	ExpiresAt time.Time      `json:"expires_at"`
	UserAgent sql.NullString `json:"user_agent"`
	IpAddress sql.NullString `json:"ip_address"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.IpAddress,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsForUser = `-- name: DeleteSessionsForUser :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteSessionsForUser(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUser, userID)
	return err
}

const deleteSessionsForUserExcept = `-- name: DeleteSessionsForUserExcept :exec
DELETE FROM sessions WHERE user_id = ? AND id != ?
`

type DeleteSessionsForUserExceptParams struct {
	UserID int64  `json:"user_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteSessionsForUserExcept(ctx context.Context, arg DeleteSessionsForUserExceptParams) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsForUserExcept, arg.UserID, arg.ID)
	return err
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = ? WHERE id = ?
`

type ExtendSessionParams struct {
	ExpiresAt time.Time `json:"expires_at"`
	ID        string    `json:"id"`
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.ID)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, expires_at, created_at, user_agent, ip_address FROM sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UserAgent,
		&i.IpAddress,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT sessions.id, sessions.user_id, sessions.expires_at, sessions.created_at, sessions.user_agent, sessions.ip_address, users.id, users.username, users.email, users.display_name, users.password_hash, users.role, users.created_at, users.updated_at, users.totp_secret_enc, users.totp_enabled, users.totp_enrolled_at
FROM sessions
INNER JOIN users ON users.id = sessions.user_id
WHERE sessions.id = ? LIMIT 1
`

type GetSessionWithUserRow struct {
	Session Session `json:"session"`
	User    User    `json:"user"`
}

func (q *Queries) GetSessionWithUser(ctx context.Context, id string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, id)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Session.ID,
		&i.Session.UserID,
		&i.Session.ExpiresAt,
		&i.Session.CreatedAt,
		&i.Session.UserAgent,
		&i.Session.IpAddress,
		&i.User.ID,
		&i.User.Username,
		&i.User.Email,
		&i.User.DisplayName,
		&i.User.PasswordHash,
		&i.User.Role,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.TotpSecretEnc,
		&i.User.TotpEnabled,
		&i.User.TotpEnrolledAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, expires_at, created_at, user_agent, ip_address FROM sessions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessionsForUser(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UserAgent,
			&i.IpAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
