// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_page_domains.sql

package store

import (
	"context"
)

const addStatusPageDomain = `-- name: AddStatusPageDomain :one
INSERT INTO status_page_domains (status_page_id, domain)
VALUES (?, ?)
RETURNING id, status_page_id, domain, created_at
`

type AddStatusPageDomainParams struct {
	StatusPageID int64  `json:"status_page_id"`
	Domain       string `json:"domain"`
}

func (q *Queries) AddStatusPageDomain(ctx context.Context, arg AddStatusPageDomainParams) (StatusPageDomain, error) {
	row := q.db.QueryRowContext(ctx, addStatusPageDomain, arg.StatusPageID, arg.Domain)
	var i StatusPageDomain
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const countAllStatusPageDomains = `-- name: CountAllStatusPageDomains :one
SELECT COUNT(*) FROM status_page_domains
`

func (q *Queries) CountAllStatusPageDomains(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllStatusPageDomains)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteStatusPageDomain = `-- name: DeleteStatusPageDomain :exec
DELETE FROM status_page_domains WHERE id = ? AND status_page_id = ?
`

type DeleteStatusPageDomainParams struct {
	ID           int64 `json:"id"`
	StatusPageID int64 `json:"status_page_id"`
}

func (q *Queries) DeleteStatusPageDomain(ctx context.Context, arg DeleteStatusPageDomainParams) error {
	_, err := q.db.ExecContext(ctx, deleteStatusPageDomain, arg.ID, arg.StatusPageID)
	return err
}

const getStatusPageDomain = `-- name: GetStatusPageDomain :one
SELECT id, status_page_id, domain, created_at FROM status_page_domains WHERE id = ? LIMIT 1
`

func (q *Queries) GetStatusPageDomain(ctx context.Context, id int64) (StatusPageDomain, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageDomain, id)
	var i StatusPageDomain
	err := row.Scan(
		&i.ID,
		&i.StatusPageID,
		&i.Domain,
		&i.CreatedAt,
	)
	return i, err
}

const listAllStatusPageDomains = `-- name: ListAllStatusPageDomains :many
SELECT id, status_page_id, domain, created_at FROM status_page_domains ORDER BY domain ASC
`

func (q *Queries) ListAllStatusPageDomains(ctx context.Context) ([]StatusPageDomain, error) {
	rows, err := q.db.QueryContext(ctx, listAllStatusPageDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageDomain{}
	for rows.Next() {
		var i StatusPageDomain
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDomainsForStatusPage = `-- name: ListDomainsForStatusPage :many
SELECT id, status_page_id, domain, created_at FROM status_page_domains
WHERE status_page_id = ?
ORDER BY domain ASC
`

func (q *Queries) ListDomainsForStatusPage(ctx context.Context, statusPageID int64) ([]StatusPageDomain, error) {
	rows, err := q.db.QueryContext(ctx, listDomainsForStatusPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPageDomain{}
	for rows.Next() {
		var i StatusPageDomain
		if err := rows.Scan(
			&i.ID,
			&i.StatusPageID,
			&i.Domain,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupStatusPageByDomain = `-- name: LookupStatusPageByDomain :one
SELECT status_pages.id, status_pages.slug, status_pages.title, status_pages.description, status_pages.logo_url, status_pages.accent_color, status_pages.custom_footer_html, status_pages.password_hash, status_pages.is_default, status_pages.created_at, status_pages.updated_at, status_pages.footer_mode, status_pages.hide_powered_by, status_pages.show_history
FROM status_pages
JOIN status_page_domains ON status_page_domains.status_page_id = status_pages.id
WHERE status_page_domains.domain = ?
LIMIT 1
`

func (q *Queries) LookupStatusPageByDomain(ctx context.Context, domain string) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, lookupStatusPageByDomain, domain)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.AccentColor,
		&i.CustomFooterHtml,
		&i.PasswordHash,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FooterMode,
		&i.HidePoweredBy,
		&i.ShowHistory,
	)
	return i, err
}
