// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_page_components.sql

package store

import (
	"context"
)

const addComponentToStatusPage = `-- name: AddComponentToStatusPage :exec
INSERT INTO status_page_components (status_page_id, component_id, display_order)
VALUES (?, ?, ?)
`

type AddComponentToStatusPageParams struct {
	StatusPageID int64 `json:"status_page_id"`
	ComponentID  int64 `json:"component_id"`
	DisplayOrder int64 `json:"display_order"`
}

func (q *Queries) AddComponentToStatusPage(ctx context.Context, arg AddComponentToStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, addComponentToStatusPage, arg.StatusPageID, arg.ComponentID, arg.DisplayOrder)
	return err
}

const listComponentsForStatusPage = `-- name: ListComponentsForStatusPage :many
SELECT components.id, components.name, components.description, components.display_order, components.created_at, components.updated_at
FROM status_page_components
JOIN components ON components.id = status_page_components.component_id
WHERE status_page_components.status_page_id = ?
ORDER BY status_page_components.display_order ASC
`

func (q *Queries) ListComponentsForStatusPage(ctx context.Context, statusPageID int64) ([]Component, error) {
	rows, err := q.db.QueryContext(ctx, listComponentsForStatusPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Component{}
	for rows.Next() {
		var i Component
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllComponentsFromStatusPage = `-- name: RemoveAllComponentsFromStatusPage :exec
DELETE FROM status_page_components WHERE status_page_id = ?
`

func (q *Queries) RemoveAllComponentsFromStatusPage(ctx context.Context, statusPageID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllComponentsFromStatusPage, statusPageID)
	return err
}

const removeComponentFromStatusPage = `-- name: RemoveComponentFromStatusPage :exec
DELETE FROM status_page_components WHERE status_page_id = ? AND component_id = ?
`

type RemoveComponentFromStatusPageParams struct {
	StatusPageID int64 `json:"status_page_id"`
	ComponentID  int64 `json:"component_id"`
}

func (q *Queries) RemoveComponentFromStatusPage(ctx context.Context, arg RemoveComponentFromStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, removeComponentFromStatusPage, arg.StatusPageID, arg.ComponentID)
	return err
}

const updateStatusPageComponentOrder = `-- name: UpdateStatusPageComponentOrder :exec
UPDATE status_page_components
SET display_order = ?
WHERE status_page_id = ? AND component_id = ?
`

type UpdateStatusPageComponentOrderParams struct {
	DisplayOrder int64 `json:"display_order"`
	StatusPageID int64 `json:"status_page_id"`
	ComponentID  int64 `json:"component_id"`
}

func (q *Queries) UpdateStatusPageComponentOrder(ctx context.Context, arg UpdateStatusPageComponentOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPageComponentOrder, arg.DisplayOrder, arg.StatusPageID, arg.ComponentID)
	return err
}
