// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_pages.sql

package store

import (
	"context"
	"database/sql"
)

const createStatusPage = `-- name: CreateStatusPage :one
INSERT INTO status_pages (
    slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default, created_at, updated_at, footer_mode
`

type CreateStatusPageParams struct {
	Slug             string         `json:"slug"`
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	LogoUrl          sql.NullString `json:"logo_url"`
	AccentColor      sql.NullString `json:"accent_color"`
	CustomFooterHtml sql.NullString `json:"custom_footer_html"`
	PasswordHash     sql.NullString `json:"password_hash"`
	IsDefault        bool           `json:"is_default"`
}

func (q *Queries) CreateStatusPage(ctx context.Context, arg CreateStatusPageParams) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, createStatusPage,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.LogoUrl,
		arg.AccentColor,
		arg.CustomFooterHtml,
		arg.PasswordHash,
		arg.IsDefault,
	)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.AccentColor,
		&i.CustomFooterHtml,
		&i.PasswordHash,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FooterMode,
	)
	return i, err
}

const deleteStatusPage = `-- name: DeleteStatusPage :exec
DELETE FROM status_pages WHERE id = ?
`

func (q *Queries) DeleteStatusPage(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStatusPage, id)
	return err
}

const getDefaultStatusPage = `-- name: GetDefaultStatusPage :one
SELECT id, slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default, created_at, updated_at, footer_mode FROM status_pages WHERE is_default = 1 LIMIT 1
`

func (q *Queries) GetDefaultStatusPage(ctx context.Context) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getDefaultStatusPage)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.AccentColor,
		&i.CustomFooterHtml,
		&i.PasswordHash,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FooterMode,
	)
	return i, err
}

const getStatusPage = `-- name: GetStatusPage :one
SELECT id, slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default, created_at, updated_at, footer_mode FROM status_pages WHERE id = ? LIMIT 1
`

func (q *Queries) GetStatusPage(ctx context.Context, id int64) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPage, id)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.AccentColor,
		&i.CustomFooterHtml,
		&i.PasswordHash,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FooterMode,
	)
	return i, err
}

const getStatusPageBySlug = `-- name: GetStatusPageBySlug :one
SELECT id, slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default, created_at, updated_at, footer_mode FROM status_pages WHERE slug = ? LIMIT 1
`

func (q *Queries) GetStatusPageBySlug(ctx context.Context, slug string) (StatusPage, error) {
	row := q.db.QueryRowContext(ctx, getStatusPageBySlug, slug)
	var i StatusPage
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.LogoUrl,
		&i.AccentColor,
		&i.CustomFooterHtml,
		&i.PasswordHash,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FooterMode,
	)
	return i, err
}

const listStatusPages = `-- name: ListStatusPages :many
SELECT id, slug, title, description, logo_url, accent_color, custom_footer_html, password_hash, is_default, created_at, updated_at, footer_mode FROM status_pages ORDER BY is_default DESC, title ASC
`

func (q *Queries) ListStatusPages(ctx context.Context) ([]StatusPage, error) {
	rows, err := q.db.QueryContext(ctx, listStatusPages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPage{}
	for rows.Next() {
		var i StatusPage
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.LogoUrl,
			&i.AccentColor,
			&i.CustomFooterHtml,
			&i.PasswordHash,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FooterMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setStatusPageAsDefault = `-- name: SetStatusPageAsDefault :exec
UPDATE status_pages SET is_default = 1, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) SetStatusPageAsDefault(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, setStatusPageAsDefault, id)
	return err
}

const unsetAllDefaults = `-- name: UnsetAllDefaults :exec
UPDATE status_pages SET is_default = 0, updated_at = CURRENT_TIMESTAMP WHERE is_default = 1
`

func (q *Queries) UnsetAllDefaults(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, unsetAllDefaults)
	return err
}

const updateStatusPage = `-- name: UpdateStatusPage :exec
UPDATE status_pages
SET title              = ?,
    description        = ?,
    logo_url           = ?,
    accent_color       = ?,
    custom_footer_html = ?,
    updated_at         = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStatusPageParams struct {
	Title            string         `json:"title"`
	Description      sql.NullString `json:"description"`
	LogoUrl          sql.NullString `json:"logo_url"`
	AccentColor      sql.NullString `json:"accent_color"`
	CustomFooterHtml sql.NullString `json:"custom_footer_html"`
	ID               int64          `json:"id"`
}

func (q *Queries) UpdateStatusPage(ctx context.Context, arg UpdateStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPage,
		arg.Title,
		arg.Description,
		arg.LogoUrl,
		arg.AccentColor,
		arg.CustomFooterHtml,
		arg.ID,
	)
	return err
}

const updateStatusPageFooterMode = `-- name: UpdateStatusPageFooterMode :exec
UPDATE status_pages
SET footer_mode = ?,
    updated_at  = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStatusPageFooterModeParams struct {
	FooterMode string `json:"footer_mode"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateStatusPageFooterMode(ctx context.Context, arg UpdateStatusPageFooterModeParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPageFooterMode, arg.FooterMode, arg.ID)
	return err
}

const updateStatusPagePassword = `-- name: UpdateStatusPagePassword :exec
UPDATE status_pages
SET password_hash = ?,
    updated_at    = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateStatusPagePasswordParams struct {
	PasswordHash sql.NullString `json:"password_hash"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdateStatusPagePassword(ctx context.Context, arg UpdateStatusPagePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusPagePassword, arg.PasswordHash, arg.ID)
	return err
}
