// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: status_page_monitors.sql

package store

import (
	"context"
)

const addMonitorToStatusPage = `-- name: AddMonitorToStatusPage :exec
INSERT INTO status_page_monitors (status_page_id, check_id, display_order)
VALUES (?, ?, ?)
`

type AddMonitorToStatusPageParams struct {
	StatusPageID int64 `json:"status_page_id"`
	CheckID      int64 `json:"check_id"`
	DisplayOrder int64 `json:"display_order"`
}

func (q *Queries) AddMonitorToStatusPage(ctx context.Context, arg AddMonitorToStatusPageParams) error {
	_, err := q.db.ExecContext(ctx, addMonitorToStatusPage, arg.StatusPageID, arg.CheckID, arg.DisplayOrder)
	return err
}

const listMonitorsForStatusPage = `-- name: ListMonitorsForStatusPage :many
SELECT checks.id, checks.name, checks.type, checks.enabled, checks.interval_seconds, checks.timeout_seconds, checks.retries, checks.failure_threshold, checks.recovery_threshold, checks.config_json, checks.component_id, checks.last_status, checks.last_latency_ms, checks.last_checked_at, checks.consecutive_failures, checks.consecutive_successes, checks.created_at, checks.updated_at, checks.push_token, checks.reopen_window_seconds, checks.reopen_mode
FROM status_page_monitors
JOIN checks ON checks.id = status_page_monitors.check_id
WHERE status_page_monitors.status_page_id = ?
ORDER BY status_page_monitors.display_order ASC, checks.id ASC
`

func (q *Queries) ListMonitorsForStatusPage(ctx context.Context, statusPageID int64) ([]Check, error) {
	rows, err := q.db.QueryContext(ctx, listMonitorsForStatusPage, statusPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Check{}
	for rows.Next() {
		var i Check
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Enabled,
			&i.IntervalSeconds,
			&i.TimeoutSeconds,
			&i.Retries,
			&i.FailureThreshold,
			&i.RecoveryThreshold,
			&i.ConfigJson,
			&i.ComponentID,
			&i.LastStatus,
			&i.LastLatencyMs,
			&i.LastCheckedAt,
			&i.ConsecutiveFailures,
			&i.ConsecutiveSuccesses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PushToken,
			&i.ReopenWindowSeconds,
			&i.ReopenMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAllMonitorsFromStatusPage = `-- name: RemoveAllMonitorsFromStatusPage :exec
DELETE FROM status_page_monitors WHERE status_page_id = ?
`

func (q *Queries) RemoveAllMonitorsFromStatusPage(ctx context.Context, statusPageID int64) error {
	_, err := q.db.ExecContext(ctx, removeAllMonitorsFromStatusPage, statusPageID)
	return err
}
