// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: system_settings.sql

package store

import (
	"context"
)

const getSystemSettings = `-- name: GetSystemSettings :one
SELECT id, incident_id_format, incident_reopen_window_seconds, incident_reopen_mode, updated_at FROM system_settings WHERE id = 1 LIMIT 1
`

func (q *Queries) GetSystemSettings(ctx context.Context) (SystemSetting, error) {
	row := q.db.QueryRowContext(ctx, getSystemSettings)
	var i SystemSetting
	err := row.Scan(
		&i.ID,
		&i.IncidentIDFormat,
		&i.IncidentReopenWindowSeconds,
		&i.IncidentReopenMode,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemSettings = `-- name: UpdateSystemSettings :exec
UPDATE system_settings
SET incident_id_format             = ?,
    incident_reopen_window_seconds = ?,
    incident_reopen_mode           = ?,
    updated_at                     = CURRENT_TIMESTAMP
WHERE id = 1
`

type UpdateSystemSettingsParams struct {
	IncidentIDFormat            string `json:"incident_id_format"`
	IncidentReopenWindowSeconds int64  `json:"incident_reopen_window_seconds"`
	IncidentReopenMode          string `json:"incident_reopen_mode"`
}

func (q *Queries) UpdateSystemSettings(ctx context.Context, arg UpdateSystemSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSystemSettings, arg.IncidentIDFormat, arg.IncidentReopenWindowSeconds, arg.IncidentReopenMode)
	return err
}
