// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users WHERE role = ?
`

func (q *Queries) CountUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, display_name, password_hash, role)
VALUES (?, ?, ?, ?, ?)
RETURNING id, username, email, display_name, password_hash, role, created_at, updated_at, totp_secret_enc, totp_enabled, totp_enrolled_at
`

type CreateUserParams struct {
	Username     string `json:"username"`
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpEnrolledAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const disableUserTOTP = `-- name: DisableUserTOTP :exec
UPDATE users
SET totp_secret_enc = NULL, totp_enabled = 0, totp_enrolled_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) DisableUserTOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, disableUserTOTP, id)
	return err
}

const enableUserTOTP = `-- name: EnableUserTOTP :exec
UPDATE users
SET totp_enabled = 1, totp_enrolled_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) EnableUserTOTP(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, enableUserTOTP, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, display_name, password_hash, role, created_at, updated_at, totp_secret_enc, totp_enabled, totp_enrolled_at FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpEnrolledAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, display_name, password_hash, role, created_at, updated_at, totp_secret_enc, totp_enabled, totp_enrolled_at FROM users WHERE id = ? LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpEnrolledAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, display_name, password_hash, role, created_at, updated_at, totp_secret_enc, totp_enabled, totp_enrolled_at FROM users WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TotpSecretEnc,
		&i.TotpEnabled,
		&i.TotpEnrolledAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, display_name, password_hash, role, created_at, updated_at, totp_secret_enc, totp_enabled, totp_enrolled_at FROM users ORDER BY created_at ASC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotpSecretEnc,
			&i.TotpEnabled,
			&i.TotpEnrolledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserTOTPSecret = `-- name: SetUserTOTPSecret :exec
UPDATE users
SET totp_secret_enc = ?, totp_enabled = 0, totp_enrolled_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type SetUserTOTPSecretParams struct {
	TotpSecretEnc sql.NullString `json:"totp_secret_enc"`
	ID            int64          `json:"id"`
}

func (q *Queries) SetUserTOTPSecret(ctx context.Context, arg SetUserTOTPSecretParams) error {
	_, err := q.db.ExecContext(ctx, setUserTOTPSecret, arg.TotpSecretEnc, arg.ID)
	return err
}

const updateUserMetadata = `-- name: UpdateUserMetadata :exec
UPDATE users
SET email = ?, display_name = ?, role = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserMetadataParams struct {
	Email       string `json:"email"`
	DisplayName string `json:"display_name"`
	Role        string `json:"role"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateUserMetadata(ctx context.Context, arg UpdateUserMetadataParams) error {
	_, err := q.db.ExecContext(ctx, updateUserMetadata,
		arg.Email,
		arg.DisplayName,
		arg.Role,
		arg.ID,
	)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role string `json:"role"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}
